#include "javascriptextensions.h"
#include "processjavascript.h"
#include <fstream>
#include "log.h"
#include "picojson.h"
#include "replaceall.h"
#include "split.h"
#include "languagemanager.h"
#include "readallfile.h"
#include "replaceall.h"
#include "fileutils.h"
#include <regex>

JavaScriptExtensions::JavaScriptExtensions()
{

}

std::string JavaScriptExtensions::GetBasicExtension(bool IsRecord)
{
    std::string additional;

    if(IsRecord)
    {
        additional += ReadAllString(GetRelativePathToExe(std::wstring(L"html/main/css_path.js")));
        additional += ReadAllString(GetRelativePathToExe(std::wstring(L"html/main/xpath_path.js")));
        additional += ReadAllString(GetRelativePathToExe(std::wstring(L"html/main/diff_match.js")));
        additional += ReadAllString(GetRelativePathToExe(std::wstring(L"html/main/multiselect.js")));
    }

    std::string original_functions = ReadAllString(GetRelativePathToExe(std::wstring(L"html/main/generate_safe_data.js")));


    std::string inspect_script;

    if(IsRecord)
    {
        inspect_script = std::string(
        ";_BAS_HIDE(BrowserAutomationStudio_CssSelectorGenerator2) = new _BAS_HIDE(CssSelectorGenerator)({selectors: ['tag', 'nthchild']});"
        ";_BAS_HIDE(BrowserAutomationStudio_CssSelectorGenerator) = new _BAS_HIDE(CssSelectorGenerator)({selectors: ['id', 'tag', 'nthchild']});"
        ";_BAS_HIDE(BrowserAutomationStudio_CssSelectorGenerator3) = new _BAS_HIDE(CssSelectorGenerator)({selectors: ['id', 'class', 'tag', 'nthchild']});"
        ";_BAS_HIDE(BrowserAutomationStudio_InspectElement) = function(x,y,position,capture_frame)"
        "{"
            "var css = '';"
            "var css2 = '';"
            "var css3 = '';"
            "var match = '';"
            "var xpath = '';"

            "var el = null;"
            "var el_target = null;"
            "var global_position = position;"

            "for(var it = 0;it<10;it++)"
            "{"
                "position = global_position;"
                "var elementsFromPointTarget = _BAS_HIDE(BrowserAutomationStudio_GetQuerySelectorHost)(el_target);"
                "var elements = _BAS_SAFE($Node.elementsFromPoint)(elementsFromPointTarget, x, y);"
                "if(elements && elements.length > 0)"
                "{"
                    "if(_BAS_SAFE($Node.shadowRoot)(elements[0]) != null)"
                    "{"
                        "position = 0;"
                    "}"
                "}"

                "if(elements && position >= 0 && position < elements.length)"
                "{"
                        "var el_new = elements[position];"
                        "if(el_new == el)"
                        "{"
                            "break;"
                        "}"
                        "el = el_new;"
                "}"
                "try"
                "{"
                    "if(css)css += ' >SHADOW> ';"
                    "css += ' >CSS> ' + _BAS_HIDE(BrowserAutomationStudio_CssSelectorGenerator).getSelector(el);"

                    "if(css2)css2 += ' >SHADOW> ';"
                    "css2 += ' >CSS> ' + _BAS_HIDE(BrowserAutomationStudio_CssSelectorGenerator2).getSelector(el);"

                    "if(css3)css3 += ' >SHADOW> ';"
                    "css3 += ' >CSS> ' + _BAS_HIDE(BrowserAutomationStudio_CssSelectorGenerator3).getSelector(el);"

                    "if(match)match += '>SHADOW>';"
                    "match += '>MATCH>' + _BAS_SAFE($String.replace)(_BAS_SAFE($String.substr)(_BAS_SAFE($Node.outerHTML)(el), 0, 40), /(?:\\r\\n|\\r|\\n)/g, ' ');"

                    "if(xpath)xpath += ' >SHADOW> ';"
                    "xpath += ' >XPATH> ' + _BAS_HIDE(BrowserAutomationStudio_CreateXPathFromElement)(el);"

                "}catch(e){};"

                "try"
                "{"
                    "let shadow = _BAS_SAFE($Node.shadowRoot)(el);"
                    "if(shadow != null)"
                    "{"
                        "el_target = shadow;"
                        "continue;"
                    "}"
                "}catch(e)"
                "{"

                "}"
                "break;"
            "}"

            "if(el){"
                "var r = _BAS_HIDE(BrowserAutomationStudio_GetInternalBoundingRect)(el);"
                "var x_with_padding = r.left;"
                "var y_with_padding = r.top;"
                "var rect = _BAS_HIDE(BrowserAutomationStudio_GetBoundingClientRect)(el);"
                "var is_frame=false;"
                "var frame_element=null;"
                "let tag = _BAS_SAFE($String.toLowerCase)(_BAS_SAFE($Node.tagName)(el));"
                "if(tag === 'iframe' || tag === 'frame')"
                "{"
                    "is_frame=true;"
                    "if(capture_frame)"
                    "{"
                        "frame_element=el;"
                    "}"
                "};"
                "var label = '';"
                "if(!is_frame)"
                "{"
                    "label += '<A>' + _BAS_SAFE($String.toUpperCase)(tag);"
                    "try"
                    "{"
                        "var id = _BAS_SAFE($Element.id)(el);"
                        "if(id && id.length > 0)"
                        "{"
                            "label += ' #' + id;"
                        "}"
                        "let className = _BAS_SAFE($Element.className)(el);"
                        "if (className)"
                        "{"
                            "let _ref = _BAS_SAFE($String.split)(className, ' ');"
                            "for (let _i = 0, _len = _ref.length; _i < _len; _i++)"
                            "{"
                                "if(_i > 2)"
                                "{"
                                    "label += ' ...';"
                                    "break;"
                                "}"
                                "let cssName = _BAS_SAFE($String.trim)(_ref[_i]);"
                                "if(cssName)"
                                "{"
                                    "label += ' .' + cssName;"
                                "}"
                            "}"
                        "}"
                    "}catch(e)"
                    "{"
                    "}"
                    "label += '</A> ';"
                "}"
                "label += css;"
                "let scroller = _BAS_HIDE(BrowserAutomationStudio_GetScrollingNode)();"
                "let scroll_left = _BAS_SAFE($Element.scrollLeft)(scroller);"
                "let scroll_top = _BAS_SAFE($Element.scrollTop)(scroller);"
                "return [_BAS_SAFE(Window.parseInt)(rect.left),_BAS_SAFE(Window.parseInt)(rect.top),_BAS_SAFE(Window.parseInt)(rect.width),_BAS_SAFE(Window.parseInt)(rect.height),label,css,css2,css3,match,xpath,x + scroll_left,y + scroll_top,true,is_frame,frame_element,x_with_padding,y_with_padding,position];"
            "}else{"
                "return [0,0,0,0,'','','','','','',x,y,false,false,null,0,0,0];"
            "}"
        "};"
        "_BAS_HIDE(BrowserAutomationStudio_SetMultiSelectData) = function(data)"
        "{"
            "_BAS_HIDE(BrowserAutomationStudio_MultiSelectData) = data;"
            "_BAS_HIDE(BrowserAutomationStudio_MultiSelectIsDirty) = true;"
        "};"
        "_BAS_HIDE(BrowserAutomationStudio_FormatSelector) = function(selector)"
        "{"
            "if(selector.length === 0)"
            "{"
                "return [];"
            "}"

            "var res = [];"

            "while(true)"
            "{"
              "var indexcss = _BAS_SAFE($String.indexOf)(selector, '>CSS>');"
              "var indexmatch = _BAS_SAFE($String.indexOf)(selector, '>MATCH>');"
              "var indexxpath = _BAS_SAFE($String.indexOf)(selector, '>XPATH>');"
              "var indexat = _BAS_SAFE($String.indexOf)(selector, '>AT>');"
              "var indexshadow = _BAS_SAFE($String.indexOf)(selector, '>SHADOW>');"

              "if(indexcss < 0 && indexmatch < 0 && indexxpath < 0 && indexat < 0 && indexshadow < 0)"
              "{"
                "break;"
              "}"

              "var allmatch = [];"
              "if(indexcss>=0)"
              "{"
                  "_BAS_SAFE($Array.push)(allmatch, indexcss);"
              "}"
              "if(indexmatch>=0)"
              "{"
                  "_BAS_SAFE($Array.push)(allmatch, indexmatch);"
              "}"
              "if(indexxpath>=0)"
              "{"
                  "_BAS_SAFE($Array.push)(allmatch, indexxpath);"
              "}"
              "if(indexat>=0)"
              "{"
                  "_BAS_SAFE($Array.push)(allmatch, indexat);"
              "}"
              "if(indexshadow>=0)"
              "{"
                  "_BAS_SAFE($Array.push)(allmatch, indexshadow);"
              "}"
              "var minindex = _BAS_SAFE(Math.min)(...allmatch);"

              "if(indexcss >= 0 && minindex === indexcss)"
              "{"
                "var item = _BAS_SAFE($String.substring)(selector, 0, indexcss);"
                "_BAS_SAFE($Array.push)(res, item, 'css');"
                "indexcss += '>CSS>'.length;"
                "selector = _BAS_SAFE($String.substring)(selector, indexcss, selector.length);"
                "continue;"
              "}"

              "if(indexmatch >= 0 && minindex === indexmatch)"
              "{"
                "var item = _BAS_SAFE($String.substring)(selector, 0, indexmatch);"
                "_BAS_SAFE($Array.push)(res, item, 'match');"
                "indexmatch += '>MATCH>'.length;"
                "selector = _BAS_SAFE($String.substring)(selector, indexmatch, selector.length);"
                "continue;"
              "}"

              "if(indexxpath >= 0 && minindex === indexxpath)"
              "{"
                "var item = _BAS_SAFE($String.substring)(selector, 0, indexxpath);"
                "_BAS_SAFE($Array.push)(res, item, 'xpath');"
                "indexxpath += '>XPATH>'.length;"
                "selector = _BAS_SAFE($String.substring)(selector, indexxpath, selector.length);"
                "continue;"
              "}"

              "if(indexat >= 0 && minindex === indexat)"
              "{"
                "var item = _BAS_SAFE($String.substring)(selector, 0, indexat);"
                "_BAS_SAFE($Array.push)(res, item, 'at');"
                "indexat += '>AT>'.length;"
                "selector = _BAS_SAFE($String.substring)(selector, indexat, selector.length);"
                "continue;"
              "}"

              "if(indexshadow >= 0 && minindex === indexshadow)"
              "{"
                "var item = _BAS_SAFE($String.substring)(selector, 0, indexshadow);"
                "_BAS_SAFE($Array.push)(res, item, 'shadow');"
                "indexshadow += '>SHADOW>'.length;"
                "selector = _BAS_SAFE($String.substring)(selector, indexshadow, selector.length);"
                "continue;"
              "}"
            "}"

            "_BAS_SAFE($Array.shift)(res);"
            "_BAS_SAFE($Array.push)(res, selector);"

            "for(var i = 0;i<res.length;i+=2)"
            "{"
                "var current = res[i];"
                "if(i + 2 < res.length && res[i+2]=== 'at')"
                "{"
                    "if(current == 'css')"
                    "{"
                        "res[i] = 'all';"
                    "}"
                    "if(current == 'match')"
                    "{"
                        "res[i] = 'match_all';"
                    "}"
                    "if(current == 'xpath')"
                    "{"
                        "res[i] = 'xpath_all';"
                    "}"
                "}"
            "}"
            "return res;"
        "};"
        "_BAS_HIDE(BrowserAutomationStudio_HighlightMultiselect) = function(need_to_get_elements)"
        "{"
            "var last_prefix = '';"
            "var shadow_prefix = '';"
            "var res = [];var data=_BAS_HIDE(BrowserAutomationStudio_MultiSelectData);var include_list=[];var exclude_list=[];var multiselect_elements=[];"
            "try{"
                "for(var i = 0;i<data.length;i++){"
                    "var item = data[i];"
                    "var selector = item.selector;"
                    "let frame_index = _BAS_SAFE($String.lastIndexOf)(selector, '>FRAME>');"

                    "if(frame_index >= 0)"
                    "{"
                        "last_prefix = _BAS_SAFE($String.substring)(selector, 0, frame_index + 7);"
                        "selector = _BAS_SAFE($String.substring)(selector, frame_index + 7, selector.length);"
                    "}"

                    "let shadow_index = _BAS_SAFE($String.lastIndexOf)(selector, '>SHADOW>');"

                    "if(shadow_index >= 0)"
                    "{"
                        "shadow_prefix = _BAS_SAFE($String.substring)(selector, 0, shadow_index + 8);"
                    "}"

                    "if(typeof(item.element) == 'undefined')"
                    "{"
                        "item.element = _BAS_HIDE(BrowserAutomationStudio_FindElement)(_BAS_SAFE(JSON.stringify)(_BAS_HIDE(BrowserAutomationStudio_FormatSelector)(selector)));"
                    "}"
                    "if(item.element)"
                    "{"
                        "_BAS_SAFE($Array.push)(multiselect_elements, item.element);"
                    "}"
                    "if(typeof(_BAS_HIDE(BrowserAutomationStudio_MultiSelectIsDirty)) == 'boolean' && _BAS_HIDE(BrowserAutomationStudio_MultiSelectIsDirty))"
                    "{"
                        "if(item.include == 1)"
                        "{"
                            "if(item.element) _BAS_SAFE($Array.push)(include_list, item.element);"
                        "}else"
                        "{"
                            "if(item.element) _BAS_SAFE($Array.push)(exclude_list, item.element);"
                        "}"
                    "}"

                    "if(item.element && _BAS_HIDE(BrowserAutomationStudio_IsVisible)(item.element, false))"
                    "{"
                        "var r = _BAS_HIDE(BrowserAutomationStudio_GetInternalBoundingRect)(item.element);"

                        "var xi = _BAS_SAFE(Window.parseInt)(r.left);"
                        "var yi = _BAS_SAFE(Window.parseInt)(r.top);"
                        "var widthi = _BAS_SAFE(Window.parseInt)(r.width);"
                        "var heighti = _BAS_SAFE(Window.parseInt)(r.height);"

                        "var x = _BAS_HIDE(BrowserAutomationStudio_ToString)(xi);"
                        "var y = _BAS_HIDE(BrowserAutomationStudio_ToString)(yi);"
                        "var width = _BAS_HIDE(BrowserAutomationStudio_ToString)(widthi);"
                        "var height = _BAS_HIDE(BrowserAutomationStudio_ToString)(heighti);"

                        "if(widthi > 0 && heighti > 0 && x.length>0 && y.length > 0 && width.length > 0 && height.length > 0)"
                        "{"
                            "_BAS_SAFE($Array.push)(res, {x:xi + 1,y:yi + 1,width:widthi + 1,height:heighti + 1,id:item.id});"
                        "}"
                    "}"
                "};"
            "}catch(e){}"
            "var result_combined = {};"
            "if(need_to_get_elements)"
            "{"
                "result_combined['elements'] = multiselect_elements;"
                "return result_combined;"
            "}"
            "result_combined['result'] = _BAS_SAFE(JSON.stringify)(res);"
            "if(typeof(_BAS_HIDE(BrowserAutomationStudio_MultiSelectIsDirty)) == 'boolean' && _BAS_HIDE(BrowserAutomationStudio_MultiSelectIsDirty) )"
            "{"
                "_BAS_HIDE(BrowserAutomationStudio_MultiSelectIsDirty) = false;"
                "if(include_list.length > 0)"
                "{"
                    "var multiselector_data = _BAS_HIDE(BrowserAutomationStudio_GenerateMultiSelectors)(include_list,exclude_list,last_prefix,shadow_prefix);"
                    "result_combined['report'] = _BAS_SAFE(JSON.stringify)(_BAS_SAFE(JSON.stringify)({include_number: include_list.length,exclude_number: exclude_list.length, data: multiselector_data}));"
                "}else"
                "{"
                    "result_combined['report'] = _BAS_SAFE(JSON.stringify)(_BAS_SAFE(JSON.stringify)({include_number: 0,exclude_number: 0}));"
                "}"
            "}"
            "return result_combined;"
        "};"
        "_BAS_HIDE(BrowserAutomationStudio_Highlight) = function(elements, index, do_scroll)"
        "{"
            "if(typeof(index) == 'undefined')"
            "{"
                "index = -1;"
            "}"
            "if(typeof(do_scroll) == 'undefined')"
            "{"
                "do_scroll = false;"
            "}"
            "if(elements && typeof(elements.length) != 'number')"
            "{"
                "elements = [elements];"
            "}"
            "var multiselect_elements = _BAS_HIDE(BrowserAutomationStudio_HighlightMultiselect)(true)['elements'];"
            "var res = '';"
            "try{"
                "for(var i = 0;i<elements.length;i++){"
                    "var el = elements[i];"
                    "var is_alternative = false;"
                    "if(index >= 0)"
                        "is_alternative = (index % elements.length) == i;"

                    "if(is_alternative && do_scroll)"
                        "_BAS_SAFE($Element.scrollIntoView)(el, {block: 'center', inline: 'center'});"

                    "if((_BAS_SAFE($Array.indexOf)(multiselect_elements, el) < 0 || is_alternative) && _BAS_HIDE(BrowserAutomationStudio_IsVisible)(el, false))"
                    "{"
                        "var r = _BAS_HIDE(BrowserAutomationStudio_GetInternalBoundingRect)(el);"

                        "var xi = _BAS_SAFE(Window.parseInt)(r.left);"
                        "var yi = _BAS_SAFE(Window.parseInt)(r.top);"
                        "var widthi = _BAS_SAFE(Window.parseInt)(r.width);"
                        "var heighti = _BAS_SAFE(Window.parseInt)(r.height);"

                        "var x =  _BAS_HIDE(BrowserAutomationStudio_ToString)(xi);"
                        "var y =  _BAS_HIDE(BrowserAutomationStudio_ToString)(yi);"
                        "var width = _BAS_HIDE(BrowserAutomationStudio_ToString)(widthi);"
                        "var height = _BAS_HIDE(BrowserAutomationStudio_ToString)(heighti);"

                        "if(widthi > 0 && heighti > 0 && x.length>0 && y.length > 0 && width.length > 0 && height.length > 0)"
                        "{"
                            "if(res.length>0)res+=';';"
                            "res += xi + ';' + yi + ';' + widthi + ';' + heighti + ';' + i + ';' + is_alternative;"
                        "}"
                    "}"
                "};"
            "}catch(e){}"
            "return res;"
        "};");
    }else
    {
        //This is a copy of record function, but without selector generation
        inspect_script = std::string(
        ";_BAS_HIDE(BrowserAutomationStudio_InspectElement) = function(x,y,position,capture_frame)"
        "{"
            "var css = '';"
            "var css2 = '';"
            "var css3 = '';"
            "var match = '';"
            "var xpath = '';"

            "var el = null;"
            "var el_target = null;"
            "var global_position = position;"

            "for(var it = 0;it<10;it++)"
            "{"
                "position = global_position;"
                "var elementsFromPointTarget = _BAS_HIDE(BrowserAutomationStudio_GetQuerySelectorHost)(el_target);"
                "var elements = _BAS_SAFE($Node.elementsFromPoint)(elementsFromPointTarget, x, y);"
                "if(elements && elements.length > 0)"
                "{"
                    "if(_BAS_SAFE($Node.shadowRoot)(elements[0]) != null)"
                    "{"
                        "position = 0;"
                    "}"
                "}"

                "if(elements && position >= 0 && position < elements.length)"
                "{"
                        "var el_new = elements[position];"
                        "if(el_new == el)"
                        "{"
                            "break;"
                        "}"
                        "el = el_new;"
                "}"
                "try"
                "{"
                    "if(css)css += ' >SHADOW> ';"
                    "css += ' >CSS> ';"

                    "if(css2)css2 += ' >SHADOW> ';"
                    "css2 += ' >CSS> ';"

                    "if(css3)css3 += ' >SHADOW> ';"
                    "css3 += ' >CSS> ';"

                    "if(match)match += '>SHADOW>';"
                    "match += '>MATCH>';"

                    "if(xpath)xpath += ' >SHADOW> ';"
                    "xpath += ' >XPATH> ';"

                "}catch(e){};"

                "try"
                "{"
                    "let shadow = _BAS_SAFE($Node.shadowRoot)(el);"
                    "if(shadow != null)"
                    "{"
                        "el_target = shadow;"
                        "continue;"
                    "}"
                "}catch(e)"
                "{"

                "}"
                "break;"
            "}"

            "if(el){"
                "var r = _BAS_HIDE(BrowserAutomationStudio_GetInternalBoundingRect)(el);"
                "var x_with_padding = r.left;"
                "var y_with_padding = r.top;"
                "var rect = _BAS_HIDE(BrowserAutomationStudio_GetBoundingClientRect)(el);"
                "var is_frame=false;"
                "var frame_element=null;"
                "let tag = _BAS_SAFE($String.toLowerCase)(_BAS_SAFE($Node.tagName)(el));"
                "if(tag === 'iframe' || tag === 'frame')"
                "{"
                    "is_frame=true;"
                    "if(capture_frame)"
                    "{"
                        "frame_element=el;"
                    "}"
                "};"
                "var label = '';"
                "if(!is_frame)"
                "{"
                    "label += '<A>' + _BAS_SAFE($String.toUpperCase)(tag);"
                    "try"
                    "{"
                        "var id = _BAS_SAFE($Element.id)(el);"
                        "if(id && id.length > 0)"
                        "{"
                            "label += ' #' + id;"
                        "}"
                        "let className = _BAS_SAFE($Element.className)(el);"
                        "if (className)"
                        "{"
                            "let _ref = _BAS_SAFE($String.split)(className, ' ');"
                            "for (let _i = 0, _len = _ref.length; _i < _len; _i++)"
                            "{"
                                "if(_i > 2)"
                                "{"
                                    "label += ' ...';"
                                    "break;"
                                "}"
                                "let cssName = _BAS_SAFE($String.trim)(_ref[_i]);"
                                "if(cssName)"
                                "{"
                                    "label += ' .' + cssName;"
                                "}"
                            "}"
                        "}"
                    "}catch(e)"
                    "{"
                    "}"
                    "label += '</A> ';"
                "}"
                "label += css;"
                "let scroller = _BAS_HIDE(BrowserAutomationStudio_GetScrollingNode)();"
                "let scroll_left = _BAS_SAFE($Element.scrollLeft)(scroller);"
                "let scroll_top = _BAS_SAFE($Element.scrollTop)(scroller);"
                "return [_BAS_SAFE(Window.parseInt)(rect.left),_BAS_SAFE(Window.parseInt)(rect.top),_BAS_SAFE(Window.parseInt)(rect.width),_BAS_SAFE(Window.parseInt)(rect.height),label,css,css2,css3,match,xpath,x + scroll_left,y + scroll_top,true,is_frame,frame_element,x_with_padding,y_with_padding,position];"
            "}else{"
                "return [0,0,0,0,'','','','','','',x,y,false,false,null,0,0,0];"
            "}"
        "};");
    }

    return
    original_functions +
    additional +
    inspect_script
     + std::string(
    "_BAS_HIDE(BrowserAutomationStudio_Evaluate) = function (expression, element) {"
        /* https://developer.mozilla.org/en-US/docs/Web/API/XPathResult#constants */
        "return _BAS_SAFE($Document.evaluate)(expression, element, null, 7, null);"
    "};"
    "_BAS_HIDE(BrowserAutomationStudio_ToString) = function (value) {"
        "if (typeof value === 'symbol') {"
            "return _BAS_SAFE($Symbol.toString)(value);"
        "}"
        "return value == null ? value.toString() : '' + value;"
    "};"
    "_BAS_HIDE(BrowserAutomationStudio_GetPageContent) = function () {"
        "return _BAS_SAFE($Node.outerHTML)(_BAS_SAFE($Document.documentElement)(document));"
    "};"
    "_BAS_HIDE(BrowserAutomationStudio_GetScrollingNode) = function () {"
        "return _BAS_SAFE($Document.scrollingElement)(document) || _BAS_SAFE($Document.documentElement)(document);"
    "};"
    "_BAS_HIDE(BrowserAutomationStudio_GetViewportStats) = function () {"
        "return ("
            "_BAS_SAFE($Element.scrollTop)(_BAS_SAFE($Document.body)(document)) + '|' +"
            "_BAS_SAFE($Element.scrollHeight)(_BAS_SAFE($Document.body)(document)) + '|' +"
            "_BAS_SAFE($Element.clientHeight)(_BAS_SAFE($Document.documentElement)(document))"
        ");"
    "};"
    "_BAS_HIDE(BrowserAutomationStudio_GetLinkUrl) = function (link) {"
        "while (link && typeof link !== 'undefined' && typeof _BAS_SAFE($Node.tagName)(link) === 'string' && _BAS_SAFE($String.toLowerCase)(_BAS_SAFE($Node.tagName)(link)) !== 'a') {"
            "link = _BAS_SAFE($Node.parentNode)(link);"
        "}"
        "if (link && typeof link !== 'undefined' && _BAS_SAFE($Node.hasAttribute)(link, 'href')) {"
            "return _BAS_SAFE($Node.getAttribute)(link, 'href');"
        "}"
        "return '';"
    "};"
    "_BAS_HIDE(BrowserAutomationStudio_IsVisible) = function (element, complex = true) {"
        "if (complex && _BAS_SAFE($Document.readyState)(document) === 'loading') return false;"
        "let style = _BAS_SAFE(Window.getComputedStyle)(element);"
        "return ("
            "style.display !== 'none' &&"
            "style.visibility !== 'hidden' &&"
            "(!complex || ((rect) => _BAS_SAFE(Math.round)(rect.width) > 0 && _BAS_SAFE(Math.round)(rect.height) > 0)(_BAS_HIDE(BrowserAutomationStudio_GetBoundingClientRect)(element)))"
        ");"
    "};"
    // This action only converts `NodeList` instances, all other types remain unchanged.
    // This is done to provide safe access to the `length` property of the target list.
    "_BAS_HIDE(BrowserAutomationStudio_ConvertIfNeeded) = function (target) {"
        "if (target && _BAS_SAFE($Object.toString)(target) === '[object NodeList]') {"
            "let result = [];"
            "for (let i = 0, length = _BAS_SAFE($NodeList.length)(target); i < length; i++) {"
                "_BAS_SAFE($Array.push)(result, target[i]);"
            "}"
            "return result;"
        "}"
        "return target;"
    "};"
    "_BAS_HIDE(BrowserAutomationStudio_GetSelectIndex) = function (element, query = null) {"
        "if (_BAS_SAFE($String.toLowerCase)(_BAS_SAFE($Node.tagName)(element)) !== 'select') throw 'wrong type';"
        "let options = _BAS_SAFE($Node.querySelectorAll)(element, 'option');"
        "let length = _BAS_SAFE($NodeList.length)(options);"
        "if (query != null) {"
            "for (let i = 0; i < length; i++) {"
                "if (_BAS_SAFE($Node.innerHTML)(options[i]) == query) {"
                    "return i;"
                "}"
            "}"
            "return -1;"
        "}"
        "return _BAS_SAFE(Math.floor)(_BAS_SAFE(Math.random)() * (length + 1));"
    "};"
    "_BAS_HIDE(BrowserAutomationStudio_GetBoundingClientRect) = function (element) {"
        "return _BAS_SAFE($DOMRectReadOnly.toJSON)(_BAS_SAFE($Element.getBoundingClientRect)(element));"
    "};"
    "_BAS_HIDE(BrowserAutomationStudio_GetInternalBoundingRect) = function(element){"
        "var style = _BAS_SAFE(Window.getComputedStyle)(element);"
        "var padding = { left: _BAS_SAFE(Window.parseInt)(style['padding-left']), right: _BAS_SAFE(Window.parseInt)(style['padding-right']), top: _BAS_SAFE(Window.parseInt)(style['padding-top']), bottom: _BAS_SAFE(Window.parseInt)(style['padding-bottom'])};"
        "var border = { left: _BAS_SAFE(Window.parseInt)(style['border-left']), right: _BAS_SAFE(Window.parseInt)(style['border-right']), top: _BAS_SAFE(Window.parseInt)(style['border-top']), bottom: _BAS_SAFE(Window.parseInt)(style['border-bottom']) };"
        "var rect = _BAS_HIDE(BrowserAutomationStudio_GetBoundingClientRect)(element);"
        "rect = {left: _BAS_SAFE(Window.parseInt)(rect.left + padding.left + border.left),right: _BAS_SAFE(Window.parseInt)(rect.right - padding.right - border.right),top: _BAS_SAFE(Window.parseInt)(rect.top + padding.top + border.top),bottom: _BAS_SAFE(Window.parseInt)(rect.bottom  - padding.top - border.top)};"
        "rect.width = rect.right - rect.left;"
        "rect.height = rect.bottom - rect.top;"
        "return rect;"
    "};"
    "_BAS_HIDE(BrowserAutomationStudio_GetElementCoordinates) = function(el)"
    "{"
        "if(el)"
        "{"
                "var rect = _BAS_HIDE(BrowserAutomationStudio_GetBoundingClientRect)(el);"

                "var xc = _BAS_SAFE(Math.floor)(rect.left + rect.width/2);"
                "var yc = _BAS_SAFE(Math.floor)(rect.top + rect.height/2);"
                "var x1 = _BAS_SAFE(Math.floor)(rect.left);"
                "var y1 = _BAS_SAFE(Math.floor)(rect.top);"
                "var x2 = _BAS_SAFE(Math.floor)(rect.right);"
                "var y2 = _BAS_SAFE(Math.floor)(rect.bottom);"

                "var res = xc + ',' + yc;"

                "if(x1<0)x1=0;"
                "if(x1>_BAS_SAFE(Window.innerWidth)-2)x1=_BAS_SAFE(Window.innerWidth)-2;"

                "if(y1<0)y1=0;"
                "if(y1>_BAS_SAFE(Window.innerHeight)-2)y1=_BAS_SAFE(Window.innerHeight)-2;"

                "if(x2<=x1)x2=x1+1;"
                "if(x2>_BAS_SAFE(Window.innerWidth)-1)x2=_BAS_SAFE(Window.innerWidth)-1;"

                "if(y2<=y1)y2=y1+1;"
                "if(y2>_BAS_SAFE(Window.innerHeight)-1)y2=_BAS_SAFE(Window.innerHeight)-1;"

                "res += ',' + x1 + ',' + y1 + ',' + x2 + ',' + y2;"

                "return res;"
        "}else{"
            "throw 'BAS_NOT_EXISTS';"
        "}"
    "};"
    ";_BAS_HIDE(BrowserAutomationStudio_GenerateMenu) = function(x,y)"
    "{"
        "var media_url = '';"
        "var link_url = '';"
        "var is_link = false;"
        "var is_edit = false;"
        "var is_media = false;"

        "var elements = _BAS_SAFE($Node.elementsFromPoint)(document, x, y);"
        "var el = null;"
        "if (elements && elements.length > 0) {"
            "el = elements[0];"
        "}"
        "if (el) {"
            "if (_BAS_SAFE($String.toLowerCase)(_BAS_SAFE($Node.tagName)(el)) == 'input') {"
                "is_edit = true;"
            "}"
            "if (_BAS_SAFE($String.toLowerCase)(_BAS_SAFE($Node.tagName)(el)) == 'img') {"
                "var element_url = _BAS_SAFE($Node.getAttribute)(el, 'src');"
                "if (!element_url) element_url='';"
                "else element_url = _BAS_SAFE($URL.href)(new _BAS_SAFE(URL)(element_url, _BAS_SAFE($Node.baseURI)(document)));"
                "is_media = true;"
                "media_url = element_url;"
            "}"
            "try {"
                "var element_url = _BAS_HIDE(BrowserAutomationStudio_GetLinkUrl)(el);"
                "if (!element_url) {"
                    "element_url = '';"
                "} else {"
                    "element_url = _BAS_SAFE($URL.href)(new _BAS_SAFE(URL)(element_url, _BAS_SAFE($Node.baseURI)(document)));"
                    "is_link = true;"
                    "link_url = element_url;"
                "}"
            "} catch (e) {};"
        "}"
        "let element_selection = _BAS_SAFE($Selection.toString)(_BAS_SAFE(Window.getSelection)());"
        "return _BAS_SAFE(JSON.stringify)({'media_url': media_url,'link_url': link_url,'is_link': is_link,'is_edit': is_edit,'is_media': is_media,'selected_text': element_selection,'curent_url':location.href});"
    "};"
    ";_BAS_HIDE(BrowserAutomationStudio_DownloadUrl) = async function(url)"
    "{"
        "let body = _BAS_SAFE($Document.body)(document);"
        "let response = await _BAS_SAFE(Window.fetch)(url);"
        "let blob = await _BAS_SAFE($Response.blob)(response);"
        "{"
            "let tag = _BAS_SAFE($Document.createElement)('a');"
            "_BAS_SAFE($HTMLAnchorElement.href)(tag, _BAS_SAFE(URL.createObjectURL)(blob));"
            "_BAS_SAFE($HTMLAnchorElement.download)(tag, 'download');"
            "_BAS_SAFE($Node.appendChild)(body, tag);"
            "_BAS_SAFE($HTMLElement.click)(tag);"
            "_BAS_SAFE($Node.removeChild)(body, tag);"
        "}"
    "};"
    "_BAS_HIDE(BrowserAutomationStudio_ScrollToCoordinates) = function(x,y,allowoutofbounds)"
    "{"
        "let $scrollTop = _BAS_SAFE($Element.scrollTop);"
        "let $scrollLeft = _BAS_SAFE($Element.scrollLeft);"
        "let scroller = _BAS_HIDE(BrowserAutomationStudio_GetScrollingNode)();"
        "try{"
            "var x = _BAS_SAFE(Math.floor)(x);"
            "var y = _BAS_SAFE(Math.floor)(y);"

            "if(x > $scrollLeft(scroller) && x < $scrollLeft(scroller) + _BAS_SAFE(Window.innerWidth) && y > $scrollTop(scroller) && y < $scrollTop(scroller) + _BAS_SAFE(Window.innerHeight))"
            "{"
                "var res = $scrollLeft(scroller) + ',' + $scrollTop(scroller) + ',' + x + ',' + y;"
                "return res;"
            "}"
            "if(typeof(allowoutofbounds) == 'undefined' || !allowoutofbounds || x >= 0)"
            "{"
                "_BAS_SAFE($Element.scrollLeft)(scroller, x - _BAS_SAFE(Window.innerWidth) / 2);"
            "}"
            "if(typeof(allowoutofbounds) == 'undefined' || !allowoutofbounds || y >= 0)"
            "{"
                "_BAS_SAFE($Element.scrollTop)(scroller, y - _BAS_SAFE(Window.innerHeight) / 2);"
            "}"
        "}catch(e)"
        "{"
            "var res = '0,0,' + x + ',' + y;"
            "return res;"
        "}"
        "{"
            "try{"
                "x-=$scrollLeft(scroller);"

                "if(typeof(allowoutofbounds) == 'undefined' || !allowoutofbounds)"
                "{"
                    "if(x<0)x=0;"
                    "if(x>_BAS_SAFE(Window.innerWidth)-2)x=_BAS_SAFE(Window.innerWidth)-2;"
                "}"

                "x+=$scrollLeft(scroller);"
                "y-=$scrollTop(scroller);"

                "if(typeof(allowoutofbounds) == 'undefined' || !allowoutofbounds)"
                "{"
                    "if(y<0)y=0;"
                    "if(y>_BAS_SAFE(Window.innerHeight)-2)y=_BAS_SAFE(Window.innerHeight)-2;"
                "}"
                "y+=$scrollTop(scroller);"

                "var res = $scrollLeft(scroller) + ',' + $scrollTop(scroller) + ',' + x + ',' + y;"
                "return res;"
            "}catch(e)"
            "{"
                "var res = '0,0,' + x + ',' + y;"
                "return res;"
            "}"
        "}"
    "}"
    ";_BAS_HIDE(BrowserAutomationStudio_ScrollToCoordinatesNoResult) = function(x,y)"
    "{"
        "let $scrollTop = _BAS_SAFE($Element.scrollTop);"
        "let $scrollLeft = _BAS_SAFE($Element.scrollLeft);"
        "let scroller = _BAS_HIDE(BrowserAutomationStudio_GetScrollingNode)();"
        "if(x > $scrollLeft(scroller) && x < $scrollLeft(scroller) + _BAS_SAFE(Window.innerWidth) && y > $scrollTop(scroller) && y < $scrollTop(scroller) + _BAS_SAFE(Window.innerHeight))"
        "{"
            "return;"
        "}"
        "$scrollLeft(scroller, x - _BAS_SAFE(Window.innerWidth) / 2);"
        "$scrollTop(scroller, y - _BAS_SAFE(Window.innerHeight) / 2);"
    "};"
    "_BAS_HIDE(BrowserAutomationStudio_ScrollUp) = function()"
    "{"
        "let scroller = _BAS_HIDE(BrowserAutomationStudio_GetScrollingNode)();"
        "_BAS_SAFE($Element.scrollTop)(scroller, _BAS_SAFE($Element.scrollTop)(scroller) - 100);"
    "};"
    "_BAS_HIDE(BrowserAutomationStudio_ScrollDown) = function()"
    "{"
        "let scroller = _BAS_HIDE(BrowserAutomationStudio_GetScrollingNode)();"
        "_BAS_SAFE($Element.scrollTop)(scroller, _BAS_SAFE($Element.scrollTop)(scroller) + 100);"
    "};"
    "_BAS_HIDE(BrowserAutomationStudio_ScrollRight) = function()"
    "{"
        "let scroller = _BAS_HIDE(BrowserAutomationStudio_GetScrollingNode)();"
        "_BAS_SAFE($Element.scrollLeft)(scroller, _BAS_SAFE($Element.scrollLeft)(scroller) + 100);"
    "};"
    "_BAS_HIDE(BrowserAutomationStudio_ScrollLeft) = function()"
    "{"
        "let scroller = _BAS_HIDE(BrowserAutomationStudio_GetScrollingNode)();"
        "_BAS_SAFE($Element.scrollLeft)(scroller, _BAS_SAFE($Element.scrollLeft)(scroller) - 100);"
    "};"
    "_BAS_HIDE(BrowserAutomationStudio_ScrollRightRight) = function()"
    "{"
        "let scroller = _BAS_HIDE(BrowserAutomationStudio_GetScrollingNode)();"
        "_BAS_SAFE($Element.scrollLeft)(scroller, _BAS_SAFE($Element.scrollLeft)(scroller) + 10000);"
    "};"
    "_BAS_HIDE(BrowserAutomationStudio_ScrollLeftLeft) = function()"
    "{"
        "let scroller = _BAS_HIDE(BrowserAutomationStudio_GetScrollingNode)();"
        "_BAS_SAFE($Element.scrollLeft)(scroller, _BAS_SAFE($Element.scrollLeft)(scroller) - 10000);"
    "};"
    "_BAS_HIDE(BrowserAutomationStudio_MatchAllIteration) = function(res,el,mask)"
    "{"
        "if (el === document) el = _BAS_SAFE($Document.body)(document);"
        "let outerHTML = _BAS_SAFE($Node.outerHTML)(el);"
        "let innerHTML = _BAS_SAFE($Node.innerHTML)(el);"
        "if(typeof(outerHTML) === 'string' && !_BAS_SAFE($String.includes)(outerHTML, mask) && typeof(innerHTML) === 'string' && !_BAS_SAFE($String.includes)(innerHTML, mask))"
            "return [];"
        "var no_child_match = true;"
        "try{"
            "for (let i = 0, nodes = _BAS_SAFE($Node.childNodes)(el); i < _BAS_SAFE($NodeList.length)(nodes); i++)"
            "{"
                "var e = nodes[i];"
                "var content = '';"
                "try{"
                    "content = _BAS_SAFE($Node.outerHTML)(e);"
                "}catch(e)"
                "{"
                    "continue;"
                "}"
                "if(!content || content.length === 0)"
                    "continue;"
                "if(_BAS_SAFE($String.includes)(content, mask))"
                "{"
                    "no_child_match = false;"
                    "_BAS_SAFE($Array.concat)(res, _BAS_HIDE(BrowserAutomationStudio_MatchAllIteration)(res, e, mask));"
                "}"
            "}"
            "if(no_child_match)"
            "{"
                "_BAS_SAFE($Array.push)(res, el);"
            "}"
        "}"
        "catch(e){"
        "}"
        "return res;"
    "};"
    "_BAS_HIDE(BrowserAutomationStudio_MatchIteration) = function(el,mask)"
    "{"
        "if (el === document) el = _BAS_SAFE($Document.body)(document);"
        "let outerHTML = _BAS_SAFE($Node.outerHTML)(el);"
        "let innerHTML = _BAS_SAFE($Node.innerHTML)(el);"
        "if(typeof(outerHTML) === 'string' && !_BAS_SAFE($String.includes)(outerHTML, mask) && typeof(innerHTML) === 'string' && !_BAS_SAFE($String.includes)(innerHTML, mask))"
            "return null;"
        "for (let i = 0, nodes = _BAS_SAFE($Node.childNodes)(el); i < _BAS_SAFE($NodeList.length)(nodes); i++)"
        "{"
            "var e = nodes[i];"
            "var content = '';"
            "try{"
                "content = _BAS_SAFE($Node.outerHTML)(e);"
            "}catch(e)"
            "{"
                "continue;"
            "}"
            "if(!content || content.length === 0)"
                "continue;"
            "if(_BAS_SAFE($String.includes)(content, mask))"
            "{"
                "return _BAS_HIDE(BrowserAutomationStudio_MatchIteration)(e,mask);"
            "}"
        "}"
        "return el;"
    "};"
    "_BAS_HIDE(BrowserAutomationStudio_GetQuerySelectorHost) = function(el, default_host)"
    "{"
        "try"
        "{"
            "let root = _BAS_SAFE($Node.getRootNode)(el);"
            "if(root instanceof _BAS_SAFE(ShadowRoot))"
            "{"
                "return root;"
            "}"
        "}catch(e)"
        "{"
        "}"
        "if(typeof(default_host) == 'undefined')"
        "{"
            "return document;"
        "}"
        "return default_host;"
    "};"
    "_BAS_HIDE(BrowserAutomationStudio_FindElement) = function(search)"
    "{"
        "try{"
            "var json = _BAS_SAFE(JSON.parse)(search);"
            "var res = document;"
            "for(var i = 0;i+1<json.length;i+=2)"
            "{"
                "var select_type = json[i];"
                "var select_value = json[i+1];"
                "if(select_type == 'xpath')"
                "{"
                    "if(!(res instanceof _BAS_SAFE(ShadowRoot)))"
                    "{"
                        "res = _BAS_SAFE($XPathResult.snapshotItem)(_BAS_HIDE(BrowserAutomationStudio_Evaluate)(select_value, res), 0);"
                    "}else"
                    "{"
                        "var found = false;"
                        "for (let j = 0, count = _BAS_SAFE($Node.childElementCount)(res); j < count; j++)"
                        "{"
                            "try"
                            "{"
                                "var q = _BAS_HIDE(BrowserAutomationStudio_Evaluate)(select_value, _BAS_SAFE($Node.children)(res)[j]);"
                                "if(_BAS_SAFE($XPathResult.snapshotLength)(q) > 0)"
                                "{"
                                    "res = _BAS_SAFE($XPathResult.snapshotItem)(q, 0);"
                                    "found = true;"
                                    "break;"
                                "}"
                            "}catch(e){}"
                        "}"
                        "if(!found)"
                        "{"
                            "res = null;"
                        "}"
                    "}"

                "}"
                "if(select_type == 'xpath_all')"
                "{"
                    "if(!(res instanceof _BAS_SAFE(ShadowRoot)))"
                    "{"
                        "var q = _BAS_HIDE(BrowserAutomationStudio_Evaluate)(select_value, res);"
                        "let len = _BAS_SAFE($XPathResult.snapshotLength)(q);res=[];"
                        "for (var it = 0;it<len;it++) _BAS_SAFE($Array.push)(res, _BAS_SAFE($XPathResult.snapshotItem)(q, it));"
                    "}else"
                    "{"
                        "var r = [];"
                        "for (let j = 0, count = _BAS_SAFE($Node.childElementCount)(res); j < count; j++)"
                        "{"
                            "try"
                            "{"
                                "var q = _BAS_HIDE(BrowserAutomationStudio_Evaluate)(select_value, _BAS_SAFE($Node.children)(res)[j]);"
                                "let len = _BAS_SAFE($XPathResult.snapshotLength)(q);"
                                "for(var it = 0;it<len;it++){"
                                    "let item = _BAS_SAFE($XPathResult.snapshotItem)(q, it);"
                                    "if (_BAS_SAFE($Array.indexOf)(r, item) < 0) _BAS_SAFE($Array.push)(r, item);"
                                "}"
                            "}catch(e){}"
                        "}"
                        "res = r;"
                    "}"
                "}"
                "if(select_type == 'css')"
                "{"
                    "res = _BAS_SAFE($Node.querySelector)(res, select_value);"
                "}"
                "if(select_type == 'all')"
                "{"
                    "res = _BAS_SAFE($Node.querySelectorAll)(res, select_value);"
                "}"
                "if(select_type == 'at')"
                "{"
                    "res = res[_BAS_SAFE(Window.parseInt)(select_value)];"
                "}"
                "if(select_type == 'shadow')"
                "{"
                    "res = _BAS_SAFE($Node.shadowRoot)(res);"
                "}"
                "if(select_type == 'match')"
                "{"
                    "res = _BAS_HIDE(BrowserAutomationStudio_MatchIteration)(res,select_value);"
                "}"
                "if(select_type == 'match_all')"
                "{"
                    "res = _BAS_HIDE(BrowserAutomationStudio_MatchAllIteration)([],res,select_value);"
                "}"
                "if(select_type == 'position')"
                "{"
                    "var x = 0;"
                    "var y = 0;"
                    "try{"
                        "x = _BAS_SAFE(Window.parseInt)(_BAS_SAFE($String.split)(select_value, ',')[0]);"
                        "y = _BAS_SAFE(Window.parseInt)(_BAS_SAFE($String.split)(select_value, ',')[1]);"
                    "}catch(e){};"
                    "_BAS_HIDE(BrowserAutomationStudio_ScrollToCoordinatesNoResult)(x,y);"
                    "let scroller = _BAS_HIDE(BrowserAutomationStudio_GetScrollingNode)();"
                    "let scroll_left = _BAS_SAFE($Element.scrollLeft)(scroller);"
                    "let scroll_top = _BAS_SAFE($Element.scrollTop)(scroller);"
                    "res = _BAS_SAFE($Node.elementFromPoint)(document, x - scroll_left, y - scroll_top);"
                "}"
                "if(!res)"
                    "return null;"
            "}"
            "if(res == document)"
                "return _BAS_SAFE($Document.body)(document);"
            "return _BAS_HIDE(BrowserAutomationStudio_ConvertIfNeeded)(res);"
        "}catch(e){return null}"
    "};");
}

std::string JavaScriptExtensions::ProcessJs(const std::string& Script, const std::string& UniqueProcessId)
{
    return ProcessJavaScript(Script, UniqueProcessId);
}

std::string JavaScriptExtensions::GetHideExtension(const std::string& UniqueProcessId)
{
    return std::string("Object.defineProperty(location.reload, '_bas_hide_") + UniqueProcessId + std::string("', { value: {} });");
}
