window.Translate = {
  "ru": {
    "Application log": "Лог приложения",
    "Use ; symbol to search for several values. For example Task name;Thread #3": "Используйте символ ; для поиска нескольких значений. Например, Название задачи;Поток №3",
    "Scheduler log": "Лог планировщика",
    "No scheduler log messages": "Нет записей в логе планировщика",
    "No applicaition log messages": "Нет записей в логе приложения",
    "No tasks created yet.": "Ни одной задачи еще не создано.",
    "There are": "В архиве есть",
    "archived records.": "записей.",
    "Show": "Показать",
    "Hide": "Спрятать",
    "Remove all archived": "Удалить все записи из архива",
    "Task is scheduled, waiting for execution.": "Задание запланировано, ожидает выполнения.",
    "Setting up application, this may take several minutes.": "Настройка приложения, это может занять несколько минут.",
    "Task is executing right now.": "Задача выполняется.",
    "Task was executed desired number of times and archived right now. This means, that it wont be scheduled any more without user interaction.": "Задача была выполнена необходимое количество раз и добавлена в архив. Это означает, что она больше не будет запланирована автоматически.",
    "Task is waiting to be scheduled.": "Определяется время запуска.",
    "scheduling": "планируется",
    "scheduled": "запланировано",
    "downloading": "загрузка",
    "executing": "выполнение",
    "archived": "в архиве",
    "Each script has total success and fail number allowed. When either success number or fail number are exceeded, script will stop. What exactly counts as success depends on the script, it could be registration number or posts count or anything else.": "Каждое приложение имеет допустимое количество успешных и неудачных выполнений. При превышении этих значений, приложение останавливается. Что именно считается успешным выполнением, зависит от приложения, это может быть регистрация аккаунта или отправка сообщения или другое событие.",
    "Successes": "Успехов",
    "Each script has total success and fail number allowed. When either success number or fail number are exceeded, script will stop. What exactly counts as fail depends on the script, it could be any error during script execution.": "Каждое приложение имеет допустимое количество успешных и неудачных выполнений. При превышении этих значений, приложение останавливается. Что именно считается неудачным выполнением, зависит от приложения, обычно это может быть любая ошибка.",
    "Fails": "Неудач",
    "Will start": "Будет запущено",
    "Downloading started": "Загрузка началась",
    "Execution started": "Выполнение началось",
    "Name :": "Название :",
    "Status :": "Статус :",
    "State :": "Состояние :",
    "Total number of the number of times the script has been started and completed.": "Общее количество раз, когда приложение было запущено и завершено.",
    "Total number script finished :": "Общее количество выполнений :",
    "Number of threads currently running": "Количество запущенных потоков",
    "Threads :": "Потоков :",
    "Number of browsers currently running": "Количество запущенных браузеров",
    "Browsers number :": "Количество браузеров :",
    "Total successes :": "Успешных выполнений :",
    "Total fails :": "Неудачных выполнений :",
    "Date and time when the script was last started": "Дата и время последнего запуска приложения",
    "Last start date :": "Дата последнего запуска :",
    "Date and time when the script will be started next time": "Дата и время, когда приложение будет запущено в следующий раз",
    "Scheduled date :": "Запланированная дата :",
    "Scheduled type :": "Тип планировки :",
    "Advanced information": "Информация",
    "Download log": "Скачать лог",
    "download log file produced by last or current run.": "скачать лог из последнего или текущего запуска.",
    "Show report": "Показать отчет",
    "show script report, it contains information about problems during last script run, running time, number of successful thread executions and other.": "показать отчет о выполнении приложения, он содержит информацию о проблемах во время последнего запуска, времени выполнения, количестве успешно завершенных потоков и прочее.",
    "download file with results, like registered users.": "скачать файл с результатами, например, список зарегистрированных пользователей.",
    "Control this schedule": "Управление заданием",
    "Stop": "Остановить",
    "stop this task instantly.": "остановить эту задачу немедленно.",
    "Start": "Запустить",
    "start this task instantly.": "запустить эту задачу мгновенно.",
    "Archive": "Поместить в архив",
    "archived tasks wont be scheduled, but wont be deleted also, so you can run it later.": "задачи в архиве не будут больше запланированы автоматически, но также не будут удалены. Вы можете запустить их позже вручную.",
    "Restore from archive": "Восстановить из архива",
    "task will be restored from archive and scheduled again.": "задание будет восстановлено из архива и снова запланировано.",
    "Edit": "Редактировать",
    "edit current task, change name, schedule, etc.": "изменить текущее задание, изменить имя, расписание и т. д.",
    "Toggle visibility": "Показать/скрыть",
    "show or hide script interface.": "показать или скрыть интерфейс приложения.",
    "Delete": "Удалить",
    "delete current task, if you planning to use it later, better use archive.": "удалить данную задачу, если вы планируете использовать ее позже, лучше добавить в архив.",
    "Task list": "Список заданий",
    "Sort by date added": "Сортировать по дате добавления",
    "Sort by date scheduled": "Сортировать по дате следующего запуска",
    "Sort by name": "Сортировать по имени",
    "Clear all tasks": "Удалить все задания",
    "Save all tasks": "Сохранить все задания в файл",
    "Load tasks": "Загрузить задания из файла",
    "Clear log": "Очистить журнал",
    "Search": "Поиск",
    "Download full log": "Скачать лог",
    "You can download application log for each task from task menu.": "Вы можете скачать лог конкретного задания из меню этой задачи.",
    "Creating new task": "Создать новую задачу",
    "Editing task": "Редактировать задачу",
    "Name": "Название",
    "Task name": "Название задачи",
    "Project": "Проект",
    "Upload project": "Загрузить проект",
    "Data": "Данные",
    "Select data for script": "Задайте данные для задачи",
    "Schedule": "График",
    "Schedule task": "Расписание выполнения задачи",
    "Task label, set it to something meaningful in order to remember its purpose:": "Название задачи, используйте такое значение, чтобы было понятно, что делает проект:",
    "Please select project source:": "Пожалуйста, выберите источник проекта:",
    "Load project from file": "Загрузить проект из файла",
    "Use project from server": "Использовать проект с сервера",
    "No project uploaded yet.": "Проект еще не загружен.",
    "Project uploaded, size": "Проект загружен, размер",
    "Remove": "Удалить",
    "Upload": "Загрузить",
    "The script name, must be exactly the same as what was entered during script creation.": "Имя приложения, оно должно совпадать с тем, которое было введено при создании.",
    "Upload new": "Загрузить новый",
    "User login which has access for current script:": "Логин пользователя, который имеет доступ к данному приложению:",
    "User password which has access for current script:": "Пароль пользователя, который имеет доступ к данному приложению:",
    "Save": "Сохранить",
    "Interface is starting and will be shown in another window. Check in task bar if you dont see it.": "Интерфейс запускается и будет показан в другом окне. Проверьте в панели задач, если вы его не видите.",
    "Cancel.": "Отменить.",
    "This script doesnt require to input any data.": "Этот приложение не требует ввода каких-либо данных.",
    "Data prepared.": "Данные введены.",
    "Change data": "Изменить данные",
    "This script requires data in order to work correctly.": "Этот приложение требует данных для правильной работы.",
    "Input data": "Задать данные",
    "Save and close": "Сохранить и закрыть",
    "Cancel": "Отменить",
    "Next": "Дальше",
    "Previous": "Назад",
    "Report for": "Отчет для задачи",
    "script": "",
    "Manual activities": "Требуется вмешательство пользователя",
    "Browser is controlled manually with message: ": "Браузер управляется в ручном режиме, сообщение: '",
    "Show browser": "Показать браузер",
    "Manual browser control is only available if you run scheduler locally.": "Ручное управление браузером доступно, только если вы запускаете планировщик локально.",
    "Run now": "Запустить сейчас",
    "Run at exact time": "Запустить в точное время",
    "Run with interval": "Запускать с интервалом",
    "Start every hour": "Запускать каждый час",
    "Start every day": "Запускать каждый день",
    "Start every week": "Запускать каждую неделю",
    "Start every month": "Запускать каждый месяц",
    "Start time list": "Список дат",
    "Run after ": "Запускать после ",
    "The task is scheduled at ": "Задача запланирована на ",
    ", do you want to update schedule?": ", вы хотите обновить расписание?",
    "Yes": "Да",
    "No": "Нет",
    "The task is already running do you want to restart it in order to apply new settings?": "Задача уже запущена. Вы хотите перезапустить ее, чтобы применить новые настройки?",
    "Project version must be at least ": "Версия проекта должна быть как минимум ",
    "Authentication succeeded": "Аутентификация прошла успешно",
    "Project doesn't have correct format": "Проект имеет неправильный формат",
    "No information about version": "Нет информации о версии",
    "Project saved": "Проект сохранен",
    "Project is empty": "Проект пустой",
    "Scheduling": "Планируется",
    "Scheduled": "Запланировано",
    "Downloading": "Загрузка",
    "Executing": "Выполнение",
    "Archived": "Помещено в архив",
    "Task was executed desired number of times and archived right now. This means, that it won't be scheduled any more without user interaction.": "Задача была выполнена необходимое количество раз и добавлена в архив. Это означает, что она больше не будет запланирована автоматически.",
    "Start date is not selected": "Дата запуска не выбрана",
    "Start date is greater than end date": "Дата начала больше даты окончания",
    "'Start every hour at' is empty": "Поле 'Запускать каждый час' не задано",
    "'Start every day at' is empty": "Поле 'Запускать каждый день' не задано",
    "'Start every week at' is empty": "Поле 'Запускать каждую неделю' не задано",
    "'Start every month at' is empty": "Поле 'Запускать каждый месяц' не задано",
    "'Start date list' is empty": "Поле 'Список дат для запуска' не задано",
    "Task name not set": "Имя задачи не установлено",
    "Are you sure, that you want to delete all archived records?": "Вы уверены, что хотите удалить все задачи из архива?",
    "Are you sure, that you want to delete this task?": "Вы уверены, что хотите удалить это задание?",
    "Are you sure, that you want to delete all records?": "Вы уверены, что хотите удалить все задания?",
    "Finished": "Завершено",
    "<a data-fail>Failed to start</a>": "<a data-fail>Не удалось запустить</a>",
    "Scheduled at <date>": "Запланировано на <date>",
    "Started": "Запущено",
    "Stopping manually ...": "Остановка вручную ...",
    "Starting manually ...": "Запуск вручную ...",
    "Restored from archive": "Восстановлено из архива",
    "Deleted": "Удалено",
    "Manually edited": "Отредактировано",
    "Restarting task ...": "Перезапуск задачи ...",
    "No script_name or script_data parameter, don't know how to start task": "Нет параметра script_name или script_data, невозможно запустить задачу",
    "No information about task schedule": "Нет информации о графике выполнения задачи",
    "New task created": "Новая задача создана",
    "Starting ...": "Запуск ...",
    "Timed out, stopping ...": "Превышено максимальное время выполнения, останавливаю ...",
    "Removed all": "Удалены все задачи",
    "Removed all archived": "Удалены все задачи из архива",
    "Task not set": "Задача не задача",
    "Date not set": "Дата не задана",
    "Monday": "Понедельник",
    "Tuesday": "Вторник",
    "Wednesday": "Среда",
    "Thursday": "Четверг",
    "Friday": "Пятница",
    "Saturday": "Суббота",
    "Sunday": "Воскресенье",
    " day of the month, ": " день месяца, ",
    " minute": " минуту",
    " minutes": " минут",
    "from ": "от ",
    " to ": " до ",
    " with probability ": " с вероятностью ",
    "Day of the month : ": "День месяца : ",
    "Day of the week : ": "День недели : ",
    "Hour : ": "Час : ",
    "Minute : ": "Минута : ",
    "Hide probability settings": "Скрыть настройки вероятности",
    "From day of the month : ": "Со дня месяца : ",
    "From day of the week : ": "Со дня недели : ",
    "From hour : ": "От часа : ",
    "From minute : ": "От минуты : ",
    "Run with probability": "Запуск с вероятностью",
    "Remove all intervals": "Удалить все интервалы",
    "Select schedule type": "Выберите тип расписания",
    "Examples": "Примеры",
    "Run task instantly and only once after creation.": "Запускать задачу мгновенно и только один раз после создания.",
    "Run at": "Запуск в",
    "Run task only once at selected date and time.": "Запускать задачу только один раз в заданное время.",
    "Select date, when task will start": "Выберите дату, когда будет запущено задание",
    "Start date": "Дата запуска",
    "Run task periodically with selected interval between each run.": "Периодически запускать задачу с заданным интервалом между каждым запуском.",
    "Intarval between each script start": "Интервал между каждым запуском",
    "Interval between each task start": "Интервал между каждым запуском",
    "If this option is checked, then time when task is being executed is a part of interval. For example, if task execution time is 7 minutes and interval is 10 minutes, then next run will be scheduled in 3 minutes in case if option is checked and in 10 in other case.": "Если настройка выбрана, то время выполнения задачи является частью интервала. Например, если время выполнения задачи составляет 7 минут, а интервал - 10 минут, то следующий запуск будет запланирован через 3 минуты, если эта настройка выбрана, и через 10 в противном случае.",
    "Task execution time is part of interval": "Время выполнения задания является частью интервала",
    "Run task every hour at selected minute.": "Запускать задание каждый час в выбранное время.",
    "List of minutes when task will be started every hour": "Список минут, когда задача будет запущена",
    "Start every hour at": "Запускать каждый час в",
    "Run task every day at selected time.": "Запускать задание каждый день в выбранное время.",
    "List of hours and minutes when task will be started every day": "Список часов и минут, когда задача будет запускаться каждый день",
    "Start every day at": "Запускать каждый день в",
    "Run task every week at selected day of the week and time.": "Запускать задание каждую неделю в выбранный день недели и время.",
    "List of timestamps when task will be started every week": "Список дат, когда задача будет запускаться каждую неделю",
    "Start every week at": "Запускать каждую неделю в",
    "Run task every month at selected day of the month and time.": "Запускать задание каждый месяц в выбранный день и время.",
    "List of timestamps when task will be started every month": "Список дат, когда задача будет запускаться каждый месяц",
    "Start every month at": "Запускать каждый месяц в",
    "Set start time list": "Задать список дат для запуска",
    "Select several timestamps to run current task.": "Выберите несколько дат для запуска текущей задачи.",
    "List of timestamps when task will be started": "Список дат, когда задача будет запущена",
    "Start date list": "Список дат для запуска",
    "Sequence": "Последовательность",
    "Run this task immediately after completing another task.": "Запустить эту задачу сразу после завершения другой заданной задачи.",
    "Task name after completing which current task will start": "Имя задачи, после завершения которой запускается текущая задача",
    "Task name to run after": "Задача после которой запустится текущая",
    "More settings": "Дополнительные настройки",
    "If task will run longer than selected time, it will be forced to stop": "Если задача будет выполняться дольше выбранного времени, она будет остановлена",
    "Maximum running time": "Максимальное время работы",
    "If single task will run longer than selected time, it will be forced to stop": "Если задача будет работать дольше, чем выбранное время, она будет остановлена",
    "Maximum running time for single task": "Максимальное время выполнения одного запуска",
    "Maximum number of times the task can be run": "Максимальное количество раз, когда задача может быть запущена",
    "Maximum run number": "Максимальное количество запусков",
    "Select date, when task sequence will start. If no date is selected, sequence will start immediately.": "Выберите дату, когда начнется последовательность выполнений задачи. Если дата не выбрана, последовательность начнется немедленно.",
    "Sequence start date": "Дата начала последовательности выполнений",
    "Select date, when task sequence will stop. If no date is selected, sequence will stop only when maximum run number is reached.": "Выберите дату, когда последовательность выполнений задачи остановится. Если дата не выбрана, последовательность остановится только при достижении максимального количества выполнений.",
    "Sequence end date": "Дата окончания последовательности выполнений",
    "Minimum interval between each task run": "Минимальный интервал между каждым запуском задачи",
    "Restore Defaults": "Значения по умолчанию",
    "Start in": "Начать через",
    "10 minutes": "10 минут",
    "Use this example": "Использовать этот пример",
    "1 hour": "1 час",
    "Start periodically with": "Начинать периодически с",
    "interval between launches": "интервалом между запусками",
    "Start each hour": "Начинать каждый час",
    "at 00:30": "в 00:30",
    "at 23:59": "в 23:59",
    "at Monday between 13:00 and 14:00": "в понедельник с 13:00 до 14:00",
    "Start on working days evenings and weekends with probability": "Запускать в рабочие дни по вечерам и на выходных с вероятностью",
    "10 times": "10 раз",
    "from now without interval": "начиная с текущего момента и без перерывов между запусками",
    "Estimated launch schedule": "Прогнозируемый график запуска",
    "And more items": "И другие значения",
    "Days :": "Дней :",
    "Set to zero": "Установить значене в ноль",
    "Hours :": "Часов :",
    "Minutes :": "Минут :",
    "Set to inifinite": "Бесконечно",
    "Day of the month :": "День месяца :",
    "Day of the week :": "День недели :",
    "Hour :": "Час :",
    "Minute :": "Минута :",
    "Probability settings allows to start task at certain task with selected probability. It also allows to specify interval, when task will start instead of exact time.": "Данная настройка позволяют запустить задачу с выбранной вероятностью. Она также позволяет указать интервал, когда задание будет запускаться вместо точного времени.",
    "To day of the month :": "До дня месяца :",
    "To day of the week :": "До дня недели :",
    "To hour :": "До часа :",
    "To minute :": "До минуты :",
    "Run probability for current period :": "Вероятность запуска для текущего периода :",
    "100%": "100%",
    "\"From\" time is greater than \"to\" time.": "Время начала больше, чем временя окончания.",
    "Task list is empty. Please create one.": "Список задач пустой.",
    "Infinite": "Бесконечно",
    " day": " день",
    " days": " дней",
    " hours": " часов",
    " hour": " час",
    "0 seconds": "0 секунд",
    "Remove all dates": "Удалить все даты",
    "Upload date list from file, each line must contain milliseconds elapsed since the epoch.": "Загрузить список дат из файла, каждая строка должна содержать миллисекунды, прошедшие от начала эпохи.",
    "Are you sure, that you want to delete this date?": "Вы уверены, что хотите удалить эту дату?",
    "Are you sure, that you want to delete all dates?": "Вы уверены, что хотите удалить все даты?",
    "Starting application": "Запуск приложения",
    "Failed to connect to scheduler.": "Не удалось запустить планировщик.",
    "Are you sure, that you want to delete this interval?": "Вы уверены, что хотите удалить этот интервал?",
    "Are you sure, that you want to delete all intervals?": "Вы уверены, что хотите удалить все интервалы?",
    "Running": "Запущено",
    "Stopped": "Остановлено",
    "What to search ?": "Что искать?",
    "Task label": "Название задачи",
    "Script name": "Название приложения",
    "Login": "Логин",
    "Password": "Пароль",
    "Captcha result": "Результат captcha",
    "Days": "Дней",
    "Day of the month": "День месяца",
    "Day of the week": "День недели",
    "at ": "в ",
    "Add start script date": "Дата запуска",
    "Are you sure, that you want to disable the scheduler? This will stop all current tasks, and new tasks will not be planned after PC reboot.": "Вы уверенны, что хотите отключить планировщик? Это остановит все текущие задачи, а новые задачи не будут планироваться после перезагрузки ПК.",
    "Disable scheduler": "Отлючить планировщик",
    "Are you sure, that you want to update scheduler? All tasks will be stopped during update.": "Вы уверены, что хотите обновить планировщик? Все задачи будут остановлены во время обновления.",
    "New version is available": "Доступна новая версия",
    "Version " : "Доступна ",
    " is available. Are you sure, that you want to update scheduler? All tasks will be stopped during update." : " версия. Вы уверены, что хотите обновить планировщик? Все задачи будут остановлены во время обновления.",
    "use recent BAS project": "загрузите проект из BAS",
    "This feature will work only if you saved project in BAS. All unsaved changes wont be fetched.": "Эта функция будет работать, только если вы предварительно сохранили проект в BAS. Все несохраненные изменения не будут загружены.",
    ", or": ", или",
    "Failed to fetch project from BAS.": "Не удалось получить проект из BAS."

  },
  "en": {
    "Task was executed desired number of times and archived right now. This means, that it wont be scheduled any more without user interaction.": "Task was executed desired number of times and archived right now. This means, that it won't be scheduled any more without user interaction.",
    "archived tasks wont be scheduled, but wont be deleted also, so you can run it later.": "archived tasks won't be scheduled, but won't be deleted also, so you can run it later.",
    "Interface is starting and will be shown in another window. Check in task bar if you dont see it.": "Interface is starting and will be shown in another window. Check in task bar if you don't see it.",
    "This script doesnt require to input any data.": "This script doesn't require to input any data.",
    "Browser is controlled manually with message: ": "Browser is controlled manually with message: '",
    "Select date, when task sequence will stop. If no date is selected, sequence will stop only when maximum run number is reached.": "Select date, when task sequence will stop. If no date is selected, sequence will stop only when 'maximum run number' is reached.",
    "This feature will work only if you saved project in BAS. All unsaved changes wont be fetched.": "This feature will work only if you saved project in BAS. All unsaved changes won't be fetched."

  }
}