<div class="container-fluid">
<%= _.template($('#input_constructor').html())({id:"url", description: tr("URL"), default_selector: "string", disable_int:true, value_string: "", help: {description: tr("String containing the URL with want to change."),examples:[{code:"https://en.wikipedia.org/wiki/URL"},{code:"</br>https://fingerprints.bablosoft.com/#testing"},{code:"</br>https://rucaptcha.com/in.php?key=1abc234de56fab7c89012d34e56fa7b8</br>&method=userrecaptcha&version=enterprise&action=verify</br>&min_score=0.3</br>&googlekey=6LfZil0UAAAAAAdm1Dpzsw9q0F11-bmervx9g5fE&pageurl=http://mysite.com/page/"}]} }) %>
<%= _.template($('#input_constructor').html())({id:"protocol", description:tr("Protocol/Scheme") + ". " + tr("Can be blank"), default_selector: "string", variants: ["-BAS-CLEAR-<br/><span style='color:gray;font-size:small'>" + tr("Remove this item from the specified URL") + "</span>","<br/>" + tr("Empty string") + "<br/><span style='color:gray;font-size:small'>" + tr("Do not change this item in the specified URL") + "</span>","https","http","wss","ws","ftps","ftp","file"], disable_int:true, value_string: "", help: {description: tr("Optional parameter.") + " " + tr("The scheme of accessing a resource, in most cases, means a network protocol."), examples:[{code:"https"},{code:"http"},{code:"ws"},{code:"ftp"},{code:tr("Empty string"), description: tr("Do not change this item in the specified URL")},{code:"-BAS-CLEAR-", description: tr("Remove this item from the specified URL")}]} }) %>
<%= _.template($('#input_constructor').html())({id:"username", description:tr("Username") + ". " + tr("Can be blank"), default_selector: "string", variants: ["-BAS-CLEAR-<br/><span style='color:gray;font-size:small'>" + tr("Remove this item from the specified URL") + "</span>","<br/>" + tr("Empty string") + "<br/><span style='color:gray;font-size:small'>" + tr("Do not change this item in the specified URL") + "</span>"], disable_int:true, value_string: "", help: {description: tr("Optional parameter.") + " " + tr("The username used to access the resource."), examples:[{code:"user1"},{code:"login321"},{code:"myname"},{code:tr("Empty string"), description: tr("Do not change this item in the specified URL")},{code:"-BAS-CLEAR-", description: tr("Remove this item from the specified URL")}]} }) %>
<%= _.template($('#input_constructor').html())({id:"password", description:tr("Password") + ". " + tr("Can be blank"), default_selector: "string", variants: ["-BAS-CLEAR-<br/><span style='color:gray;font-size:small'>" + tr("Remove this item from the specified URL") + "</span>","<br/>" + tr("Empty string") + "<br/><span style='color:gray;font-size:small'>" + tr("Do not change this item in the specified URL") + "</span>"], disable_int:true, value_string: "", help: {description: tr("Optional parameter.") + " " + tr("The password for the specified user."), examples:[{code:"pass123"},{code:"mypassword111"},{code:"goodpass"},{code:tr("Empty string"), description: tr("Do not change this item in the specified URL")},{code:"-BAS-CLEAR-", description: tr("Remove this item from the specified URL")}]} }) %>
<%= _.template($('#input_constructor').html())({id:"host", description:tr("Host") + ". " + tr("Can be blank"), default_selector: "string", variants: ["-BAS-CLEAR-<br/><span style='color:gray;font-size:small'>" + tr("Remove this item from the specified URL") + "</span>","<br/>" + tr("Empty string") + "<br/><span style='color:gray;font-size:small'>" + tr("Do not change this item in the specified URL") + "</span>"], disable_int:true, value_string: "", help: {description: tr("Optional parameter.") + " " + tr("Hostname or ip (IPv4 or IPv6)."), examples:[{code:"en.wikipedia.org"},{code:"fingerprints.bablosoft.com"},{code:"rucaptcha.com"},{code:"127.0.0.1"},{code:"[2a00:1450:4025:401::67]"},{code:tr("Empty string"), description: tr("Do not change this item in the specified URL")},{code:"-BAS-CLEAR-", description: tr("Remove this item from the specified URL")}]} }) %>
<%= _.template($('#input_constructor').html())({id:"port", description:tr("Port") + ". " + tr("Can be blank"), default_selector: "string", variants: ["-BAS-CLEAR-<br/><span style='color:gray;font-size:small'>" + tr("Remove this item from the specified URL") + "</span>","<br/>" + tr("Empty string") + "<br/><span style='color:gray;font-size:small'>" + tr("Do not change this item in the specified URL") + "</span>","80","443","21","70"], value_string: "", help: {description: tr("Optional parameter.") + " " + tr("Resource port."), examples:[{code:80},{code:443},{code:21},{code:tr("Empty string"), description: tr("Do not change this item in the specified URL")},{code:"-BAS-CLEAR-", description: tr("Remove this item from the specified URL")}]} }) %>
<%= _.template($('#input_constructor').html())({id:"path", description:tr("Path") + ". " + tr("Can be blank"), default_selector: "string", variants: ["-BAS-CLEAR-<br/><span style='color:gray;font-size:small'>" + tr("Remove this item from the specified URL") + "</span>","<br/>" + tr("Empty string") + "<br/><span style='color:gray;font-size:small'>" + tr("Do not change this item in the specified URL") + "</span>"], disable_int:true, value_string: "", help: {description: tr("Optional parameter.") + " " + tr("The path specifying information about the location of the resource."), examples:[{code:"/wiki/URL"},{code:"/"},{code:"/in.php"},{code:tr("Empty string"), description: tr("Do not change this item in the specified URL")},{code:"-BAS-CLEAR-", description: tr("Remove this item from the specified URL")}]} }) %>
<%= _.template($('#input_constructor').html())({id:"query", description:tr("Query") + ". " + tr("Can be blank"), default_selector: "string", variants: ["-BAS-CLEAR-<br/><span style='color:gray;font-size:small'>" + tr("Remove this item from the specified URL") + "</span>","<br/>" + tr("Empty string") + "<br/><span style='color:gray;font-size:small'>" + tr("Do not change this item in the specified URL") + "</span>"], disable_int:true, value_string: "", help: {description: tr("Optional parameter.") + " " + tr("Object or query string.") + " " + tr("The query is the part of the URL that starts with the \"?\" character, parameters are separated by \"&\", and parameter name and value are separated by \"=\"."), examples:[{code:"{\"foo\":\"bar\"}"},{code:"</br>{\"query\":\"string\"}"},{code:"</br>sitekey=10000000-ffff-ffff-ffff-000000000001&pageurl=http://mysite.com/register"},{code:"</br>" + tr("Empty string"), description: tr("Do not change this item in the specified URL")},{code:"</br>" + "-BAS-CLEAR-", description: tr("Remove this item from the specified URL")},{code:"</br>" + "{\"c\": \"-BAS-CLEAR-\"}", description: tr("Remove the \"c\" item from the query if the \"Clear old query string\" parameter is disabled")}]} }) %>
<span data-preserve="true" data-preserve-type="check" data-preserve-id="Check3">
	<input type="checkbox" id="Check3" checked="checked" style="margin-left:25px"/> <label for="Check3" class="tr">Clear old query string</label> <i class="fa fa-question-circle help-input" data-toggle="tooltip" data-html="true" title="<%= _.escape(_.template($("#tooltip-input").html())({title:tr("Clear old query string"),description:tr("If enabled, when specifying the \"Query\" parameter, its value will completely replace the old query string. If deactivated, when specifying the \"Query\" parameter, its value will be merged with the value of the old query string."),examples:[{code:tr("Activated"),description:"URL <code style=\"font-size:85%\">\"https://site.com/?a=b&c=d\"</code> " + tr("will be changed to") + " <code style=\"font-size:85%\">\"https://site.com/?f=g\"</code>, " + tr("if the query is") + " <code style=\"font-size:85%\">\"f=g\"</code> " + tr("or") + " <code style=\"font-size:85%\">{\"f\":\"g\"}</code>"},{code:"<br/>" + tr("Deactivated"),description:"URL <code style=\"font-size:85%\">\"https://site.com/?a=b&c=d\"</code> " + tr("will be changed to") + " <code style=\"font-size:85%\">\"https://site.com/?a=b&c=d&f=g\"</code>, " + tr("if the query is") + " <code style=\"font-size:85%\">\"f=g\"</code> " + tr("or") + " <code style=\"font-size:85%\">{\"f\":\"g\"}</code>"}]})) %>"></i>
</span>
<%= _.template($('#input_constructor').html())({id:"hash", description:tr("Fragment") + ". " + tr("Can be blank"), default_selector: "string", variants: ["-BAS-CLEAR-<br/><span style='color:gray;font-size:small'>" + tr("Remove this item from the specified URL") + "</span>","<br/>" + tr("Empty string") + "<br/><span style='color:gray;font-size:small'>" + tr("Do not change this item in the specified URL") + "</span>"], disable_int:true, value_string: "", help: {description: tr("Optional parameter.") + " " + tr("Fragment is the part of the URL that starts with the \"#\" character and can indicate a title within a document or the id attribute of an element. Following the link with the fragment, the browser will open the page and move the window to the specified element."), examples:[{code:"info"},{code:"testing"},{code:"solving_recaptcha_enterprise"},{code:tr("Empty string"), description: tr("Do not change this item in the specified URL")},{code:"-BAS-CLEAR-", description: tr("Remove this item from the specified URL")}]} }) %>
<%= _.template($('#block_start').html())({id:"Additional", name: tr("Additional settings"), description: ""}) %>
<%= _.template($('#input_constructor').html())({id:"base_url", description: tr("Base URL"), default_selector: "string", disable_int:true, value_string: "", help: {description: tr("Optional parameter.") + " " + tr("The URL used when the main URL is relative."),examples:[{code:"https://en.wikipedia.org"},{code:"https://fingerprints.bablosoft.com"},{code:"https://rucaptcha.com"}]} }) %>
<div><span data-preserve="true" data-preserve-type="check" data-preserve-id="Check">
	<input type="checkbox" id="Check" checked="checked" style="margin-left:25px"/> <label for="Check" class="tr">Normalize URL before changing</label>
</span></div>
<div><span data-preserve="true" data-preserve-type="check" data-preserve-id="Check2">
	<input type="checkbox" id="Check2" checked="checked" style="margin-left:25px"/> <label for="Check2" class="tr">Complete action with fail if an invalid URL is specified</label>
</span></div>
<%= _.template($('#block_end').html())() %>
<%= _.template($('#variable_constructor').html())({id:"Save", description:tr("Variable to save the result"), default_variable: "CHANGED_URL", help: {description: tr("Variable in which, after successful execution of the action, the final URL will be written."), examples:[{code:"https://en.wikipedia.org/wiki/URL"},{code:"</br>http://fingerprints.bablosoft.com/#testing"},{code:"</br>http://rucaptcha.com/in.php?key=1abc234de56fab7c89012d34e56fa7b8</br>&method=userrecaptcha&version=enterprise&action=verify</br>&min_score=0.3</br>&googlekey=6LfZil0UAAAAAAdm1Dpzsw9q0F11-bmervx9g5fE&pageurl=http://mysite.com/page"}]} }) %>
</div>
<div class="tooltipinternal">
	<div class="tr tooltip-paragraph-first-fold">Change the items of the specified URL.</div>
	<div class="tooltip-paragraph-fold"><span class="tr">This action will return a string containing the changed URL.</span> <span class="tr">You can learn more about URL in <a href="#" onclick="BrowserAutomationStudio_OpenUrl('https://en.wikipedia.org/wiki/URL');return false">Wiki</a>.</span></div>
	<div class="tr tooltip-paragraph-fold">Specify new values for the items to be changed in the URL, specify <code>"-BAS-CLEAR-"</code> if the item needs to be removed, leave the field blank if the item does not need to be changed.</div>
	<div class="tr tooltip-paragraph-fold">The query must be specified as an object, where the key is the name of the parameter and the value is the value of the parameter, example: <code>{"foo":"bar"}</code>. Or as a string, in which parameters are separated by "&amp;", and the parameter name and its value are separated by "=", example: <code>"foo=bar"</code>.</div>
	<div class="tr tooltip-paragraph-fold">If the "Clear old query string" parameter is activated, then when the "Query" parameter is specified, its value will completely replace the old query string in the specified URL.</div>
	<div class="tr tooltip-paragraph-fold">For example, if the URL is <code>"https://site.com/?a=b"</code>, the query is <code>{"c":"d"}</code> and the "Clear old query string" parameter is activated, then the action will return <code>"https://site.com/?c=d"</code>.</div>
	<div class="tr tooltip-paragraph-fold">If the "Clear old query string" parameter is disabled, specifying the "Query" parameter will merge its value with the value of the old query string in the specified URL. If an item with the same name is present in both the old and the new query, then only the value from the new query will be added to the final URL. Items present only in the old or only in the new query will be added to the final URL unchanged. Items new query containing <code>"-BAS-CLEAR-"</code> will be removed from the final URL.</div>
	<div class="tr tooltip-paragraph-fold">For example, if the URL is <code>"https://site.com/?a=b&c=d&e=f"</code>, the query is <code>{"a":"i","c":"-BAS-CLEAR-","g":"h"}</code> and the "Clear old query string" parameter is disabled, then the action will return <code>"https://site.com/?a=i&e=f&g=h"</code>.</div>
	<div class="tooltip-paragraph-fold"><span class="tr">Before changing, you can normalize the URL by activating the corresponding parameter in the additional settings, or use the "Normalize URL" action for flexible normalization.</span> <span class="tr">You can learn more about the URL normalization in <a href="#" onclick="BrowserAutomationStudio_OpenUrl('https://en.wikipedia.org/wiki/URI_normalization');return false">Wiki</a>.</span></div>
	<div class="tr tooltip-paragraph-fold">You can parse a link to items using the "Parse URL" action.</div>
	<div class="tr tooltip-paragraph-fold">You can generate a link from items using the "Generate URL" action.</div>
	<div class="tr tooltip-paragraph-last-fold">If an invalid URL is specified, the thread will stop with fail message. If you want to continue thread, use "Ignore errors" action, or deactivate the corresponding parameter in the additional settings.</div>
</div>
<%= _.template($('#back').html())({action:"executeandadd", visible:true}) %>
