<div class="container-fluid">
<%= _.template($('#input_constructor').html())({id:"protocol", description:tr("Protocol/Scheme") + ". " + tr("Can be blank"), default_selector: "string", variants: ["https","http","wss","ws","ftps","ftp","file"], disable_int:true, value_string: "", help: {description: tr("Optional parameter.") + " " + tr("The scheme of accessing a resource, in most cases, means a network protocol."), examples:[{code:"https"},{code:"http"},{code:"ws"},{code:"ftp"},{code:tr("Empty string"), description: tr("Don't add this item to the final URL")}]} }) %>
<%= _.template($('#input_constructor').html())({id:"username", description:tr("Username") + ". " + tr("Can be blank"), default_selector: "string", disable_int:true, value_string: "", help: {description: tr("Optional parameter.") + " " + tr("The username used to access the resource."), examples:[{code:"user1"},{code:"login321"},{code:"myname"},{code:tr("Empty string"), description: tr("Don't add this item to the final URL")}]} }) %>
<%= _.template($('#input_constructor').html())({id:"password", description:tr("Password") + ". " + tr("Can be blank"), default_selector: "string", disable_int:true, value_string: "", help: {description: tr("Optional parameter.") + " " + tr("The password for the specified user."), examples:[{code:"pass123"},{code:"mypassword111"},{code:"goodpass"},{code:tr("Empty string"), description: tr("Don't add this item to the final URL")}]} }) %>
<%= _.template($('#input_constructor').html())({id:"host", description:tr("Host") + ". " + tr("Can be blank"), default_selector: "string", disable_int:true, value_string: "", help: {description: tr("Optional parameter.") + " " + tr("Hostname or ip (IPv4 or IPv6)."), examples:[{code:"en.wikipedia.org"},{code:"fingerprints.bablosoft.com"},{code:"rucaptcha.com"},{code:"127.0.0.1"},{code:"[2a00:1450:4025:401::67]"},{code:tr("Empty string"), description: tr("Don't add this item to the final URL")}]} }) %>
<%= _.template($('#input_constructor').html())({id:"port", description:tr("Port") + ". " + tr("Can be blank"), default_selector: "string", variants: ["80","443","21","70"], value_string: "", help: {description: tr("Optional parameter.") + " " + tr("Resource port."), examples:[{code:80},{code:443},{code:21},{code:tr("Empty string"), description: tr("Don't add this item to the final URL")}]} }) %>
<%= _.template($('#input_constructor').html())({id:"path", description:tr("Path") + ". " + tr("Can be blank"), default_selector: "string", disable_int:true, value_string: "", help: {description: tr("Optional parameter.") + " " + tr("The path specifying information about the location of the resource."), examples:[{code:"/wiki/URL"},{code:"/"},{code:"/in.php"},{code:tr("Empty string"), description: tr("Don't add this item to the final URL")}]} }) %>
<%= _.template($('#input_constructor').html())({id:"query", description:tr("Query") + ". " + tr("Can be blank"), default_selector: "string", disable_int:true, value_string: "", help: {description: tr("Optional parameter.") + " " + tr("Object or query string.") + " " + tr("The query is the part of the URL that starts with the \"?\" character, parameters are separated by \"&\", and parameter name and value are separated by \"=\"."), examples:[{code:"{\"foo\":\"bar\"}"},{code:"</br>{\"query\":\"string\"}"},{code:"</br>sitekey=10000000-ffff-ffff-ffff-000000000001&pageurl=http://mysite.com/register"},{code:"</br>" + tr("Empty string"), description: tr("Don't add this item to the final URL")}]} }) %>
<%= _.template($('#input_constructor').html())({id:"hash", description:tr("Fragment") + ". " + tr("Can be blank"), default_selector: "string", disable_int:true, value_string: "", help: {description: tr("Optional parameter.") + " " + tr("Fragment is the part of the URL that starts with the \"#\" character and can indicate a title within a document or the id attribute of an element. Following the link with the fragment, the browser will open the page and move the window to the specified element."), examples:[{code:"info"},{code:"testing"},{code:"solving_recaptcha_enterprise"},{code:tr("Empty string"), description: tr("Don't add this item to the final URL")}]} }) %>
<%= _.template($('#variable_constructor').html())({id:"Save", description:tr("Variable to save the result"), default_variable: "GENERATED_URL", help: {description: tr("Variable in which, after successful execution of the action, the final URL will be written."), examples:[{code:"https://en.wikipedia.org/wiki/URL"},{code:"</br>http://fingerprints.bablosoft.com/#testing"},{code:"</br>http://rucaptcha.com/in.php?key=1abc234de56fab7c89012d34e56fa7b8</br>&method=userrecaptcha&version=enterprise&action=verify</br>&min_score=0.3</br>&googlekey=6LfZil0UAAAAAAdm1Dpzsw9q0F11-bmervx9g5fE&pageurl=http://mysite.com/page"}]} }) %>
</div>
<div class="tooltipinternal">
	<div class="tr tooltip-paragraph-first-fold">Generate URL from specified items.</div>
	<div class="tooltip-paragraph-fold"><span class="tr">This action will return a string containing the final URL.</span> <span class="tr">You can learn more about URL in <a href="#" onclick="BrowserAutomationStudio_OpenUrl('https://en.wikipedia.org/wiki/URL');return false">Wiki</a>.</span></div>
	<div class="tr tooltip-paragraph-fold">Specify values for the items need to be added to the URL, leave empty items that do not need to be added.</div>
	<div class="tr tooltip-paragraph-fold">The query must be specified as an object, where the key is the name of the parameter and the value is the value of the parameter, example: <code>{"foo":"bar"}</code>. Or as a string, in which parameters are separated by "&amp;", and the parameter name and its value are separated by "=", example: <code>"foo=bar"</code>.</div>
	<div class="tr tooltip-paragraph-fold">You can parse a link to items using the "Parse URL" action.</div>
	<div class="tr tooltip-paragraph-last-fold">You can change link items using the "Change URL" action.</div>
</div>
<%= _.template($('#back').html())({action:"executeandadd", visible:true}) %>
