<div class="container-fluid">
<%= _.template($('#input_constructor').html())({id:"url", description: "URL", default_selector: "string", disable_int:true, value_string: "", help: {description: tr("String containing the URL with want to normalize."),examples:[{code:"https://en.wikipedia.org/wiki/URL/"},{code:"</br>//fingerprints.bablosoft.com/#testing/"},{code:"</br>rucaptcha.com/in.php?key=1abc234de56fab7c89012d34e56fa7b8</br>&method=userrecaptcha&version=enterprise&action=verify</br>&min_score=0.3</br>&googlekey=6LfZil0UAAAAAAdm1Dpzsw9q0F11-bmervx9g5fE&pageurl=http://mysite.com/page/"}]} }) %>
<%= _.template($('#input_constructor').html())({id:"default_protocol", description: tr("Default protocol"), variants:["https","http","wss","ws","ftps","ftp","file"], default_selector: "string", disable_int:true, value_string: "http", help: {description: tr("The protocol to be added if the URL does not contain one."),examples:[{code:"http",description:"URL <code style=\"font-size:85%\">testsite.com/</code> " + tr("will be normalized to") + " <code style=\"font-size:85%\">http://testsite.com</code>"},{code:"https",description:"URL <code style=\"font-size:85%\">testsite.com</code> " + tr("will be normalized to") + " <code style=\"font-size:85%\">https://testsite.com</code>"}]} }) %>
<%= _.template($('#input_constructor').html())({id:"base_url", description: tr("Base URL") + ". " + tr("Can be blank"), default_selector: "string", disable_int:true, value_string: "", help: {description: tr("Optional parameter.") + " " + tr("The URL used when the main URL is relative."),examples:[{code:"https://en.wikipedia.org"},{code:"https://fingerprints.bablosoft.com"},{code:"https://rucaptcha.com"}]} }) %>
<%= _.template($('#input_constructor').html())({id:"remove_query_parameters", description: tr("Remove query parameters") + ". " + tr("Can be blank"), default_selector: "expression", disable_int:true, value_string: "[/^utm_\w+/i]", help: {description: tr("Optional parameter.") + " " + tr("List of strings or regular expressions.") + " " + tr("Query parameters whose names match any of the specified list items will be removed.") + " " + tr("As a list, you can use a string consisting of the names of the query parameters, separated by commas."),examples:[{code:"[/^utm_\w+/i]"},{code:"[\"foo\", \"ref\"]"},{code:"[\"bar\", \"test\"]"},{code:"foo, bar, top"},{code:"test,ref,bottom"},{code:tr("Empty string"),description:tr("Don't remove query parameters")}]} }) %>
<%= _.template($('#input_constructor').html())({id:"remove_directory_index", description: tr("Remove directory index") + ". " + tr("Can be blank"), default_selector: "expression", disable_int:true, value_string: "[/^index\.[a-z]+$/]", help: {description: tr("Optional parameter.") + " " + tr("List of strings or regular expressions.") + " " + tr("Directory indexes that match any of the specified list items will be removed.") + " " + tr("As a list, you can use a string consisting of directory indexes, separated by commas."),examples:[{code:"[/^index\.[a-z]+$/]"},{code:"[/^default\.[a-z]+$/]"},{code:"[\"index.php\", \"default.php\"]"},{code:"index.html, index.php, default.php"},{code:"index.html,index.php,default.php"},{code:tr("Empty string"),description:tr("Don't remove directory index")}]} }) %>
<div><span data-preserve="true" data-preserve-type="check" data-preserve-id="Check">
	<input type="checkbox" id="Check" checked="checked"/> <label for="Check" class="tr">Normalize protocol</label> <i class="fa fa-question-circle help-input" data-toggle="tooltip" data-html="true" title="<%= _.escape(_.template($("#tooltip-input").html())({title:tr("Normalize protocol"),description:tr("If enabled and the URL contains a relative protocol, then the protocol from the \"Default protocol\" parameter will be added to the URL."),examples:[{code:tr("Activated"),description:"URL <code style=\"font-size:85%\">//testsite.com/</code> " + tr("will be normalized to") + " <code style=\"font-size:85%\">http://testsite.com</code>"},{code:"<br/>" + tr("Deactivated"),description:"URL <code style=\"font-size:85%\">//testsite.com/</code> " + tr("will be normalized to") + " <code style=\"font-size:85%\">//testsite.com</code>"}]})) %>"></i>
</span></div>
<div><span data-preserve="true" data-preserve-type="check" data-preserve-id="Check11">
	<input type="radio" checked="checked" name="force" id="Check11" style="margin-left:20px"/> <label for="Check11" class="tr">No forced protocol change</label>
</span></div>
<div><span data-preserve="true" data-preserve-type="check" data-preserve-id="Check2">
	<input type="radio" name="force" id="Check2"/> <label for="Check2" class="tr">Force http</label> <i class="fa fa-question-circle help-input" data-toggle="tooltip" data-html="true" title="<%= _.escape(_.template($("#tooltip-input").html())({title:tr("Force http"),description:tr("If enabled, the https protocol will be replaced with http in the URL."),examples:[{code:tr("Activated"),description:"URL <code style=\"font-size:85%\">https://testsite.com/</code> " + tr("will be normalized to") + " <code style=\"font-size:85%\">http://testsite.com</code>"},{code:"<br/>" + tr("Deactivated"),description:"URL <code style=\"font-size:85%\">https://testsite.com/</code> " + tr("will be normalized to") + " <code style=\"font-size:85%\">https://testsite.com</code>"}]})) %>"></i>
</span></div>
<div><span data-preserve="true" data-preserve-type="check" data-preserve-id="Check3">
	<input type="radio" name="force" id="Check3"/> <label for="Check3" class="tr">Force https</label> <i class="fa fa-question-circle help-input" data-toggle="tooltip" data-html="true" title="<%= _.escape(_.template($("#tooltip-input").html())({title:tr("Force https"),description:tr("If enabled, the http protocol will be replaced with https in the URL."),examples:[{code:tr("Activated"),description:"URL <code style=\"font-size:85%\">http://testsite.com/</code> " + tr("will be normalized to") + " <code style=\"font-size:85%\">https://testsite.com</code>"},{code:"<br/>" + tr("Deactivated"),description:"URL <code style=\"font-size:85%\">http://testsite.com/</code> " + tr("will be normalized to") + " <code style=\"font-size:85%\">http://testsite.com</code>"}]})) %>"></i>
</span></div>
<div><span data-preserve="true" data-preserve-type="check" data-preserve-id="Check4">
	<input type="checkbox" id="Check4" checked="checked"/> <label for="Check4" class="tr">Strip authentication</label> <i class="fa fa-question-circle help-input" data-toggle="tooltip" data-html="true" title="<%= _.escape(_.template($("#tooltip-input").html())({title:tr("Strip authentication"),description:tr("If enabled, authentication data will be stripped from the URL."),examples:[{code:tr("Activated"),description:"URL <code style=\"font-size:85%\">user:pass@testsite.com/</code> " + tr("will be normalized to") + " <code style=\"font-size:85%\">http://testsite.com</code>"},{code:"<br/>" + tr("Deactivated"),description:"URL <code style=\"font-size:85%\">user:pass@testsite.com/</code> " + tr("will be normalized to") + " <code style=\"font-size:85%\">http://user:pass@testsite.com</code>"}]})) %>"></i>
</span></div>
<div><span data-preserve="true" data-preserve-type="check" data-preserve-id="Check5">
	<input type="checkbox" id="Check5"/> <label for="Check5" class="tr">Strip query</label> <i class="fa fa-question-circle help-input" data-toggle="tooltip" data-html="true" title="<%= _.escape(_.template($("#tooltip-input").html())({title:tr("Strip query"),description:tr("If enabled, the query will be stripped from the URL."),examples:[{code:tr("Activated"),description:"URL <code style=\"font-size:85%\">https://testsite.com/api.php?a=one&b=two&c=three</code> " + tr("will be normalized to") + " <code style=\"font-size:85%\">https://testsite.com/api.php</code>"},{code:"<br/>" + tr("Deactivated"),description:"URL <code style=\"font-size:85%\">testsite.com/api.php?a=one&b=two&c=three</code> " + tr("will be normalized to") + " <code style=\"font-size:85%\">http://testsite.com/api.php?a=one&b=two&c=three</code>"}]})) %>"></i>
</span></div>
<div><span data-preserve="true" data-preserve-type="check" data-preserve-id="Check6">
	<input type="checkbox" id="Check6" style="margin-left:20px"/> <label for="Check6" class="tr">Strip fragment</label> <i class="fa fa-question-circle help-input" data-toggle="tooltip" data-html="true" title="<%= _.escape(_.template($("#tooltip-input").html())({title:tr("Strip fragment"),description:tr("If enabled, the fragment will be stripped from the URL."),examples:[{code:tr("Activated"),description:"URL <code style=\"font-size:85%\">testsite.com/info.html#fragment</code> " + tr("will be normalized to") + " <code style=\"font-size:85%\">http://testsite.com/info.html</code>"},{code:"<br/>" + tr("Deactivated"),description:"URL <code style=\"font-size:85%\">testsite.com/info.html#fragment</code> " + tr("will be normalized to") + " <code style=\"font-size:85%\">http://testsite.com/info.html#fragment</code>"}]})) %>"></i>
</span></div>
<div><span data-preserve="true" data-preserve-type="check" data-preserve-id="Check7">
	<input type="checkbox" id="Check7" style="margin-left:20px"/> <label for="Check7" class="tr">Strip protocol</label> <i class="fa fa-question-circle help-input" data-toggle="tooltip" data-html="true" title="<%= _.escape(_.template($("#tooltip-input").html())({title:tr("Strip protocol"),description:tr("If enabled, the protocol will be stripped from the URL."),examples:[{code:tr("Activated"),description:"URL <code style=\"font-size:85%\">https://testsite.com/</code> " + tr("will be normalized to") + " <code style=\"font-size:85%\">testsite.com</code>"},{code:"<br/>" + tr("Deactivated"),description:"URL <code style=\"font-size:85%\">https://testsite.com/</code> " + tr("will be normalized to") + " <code style=\"font-size:85%\">https://testsite.com</code>"}]})) %>"></i>
</span></div>
<div><span data-preserve="true" data-preserve-type="check" data-preserve-id="Check8">
	<input type="checkbox" id="Check8" checked="checked" style="margin-left:20px"/> <label for="Check8" class="tr">Strip WWW</label> <i class="fa fa-question-circle help-input" data-toggle="tooltip" data-html="true" title="<%= _.escape(_.template($("#tooltip-input").html())({title:tr("Strip WWW"),description:tr("If enabled, the WWW will be stripped from the URL."),examples:[{code:tr("Activated"),description:"URL <code style=\"font-size:85%\">https://www.testsite.com/</code> " + tr("will be normalized to") + " <code style=\"font-size:85%\">https://testsite.com</code>"},{code:"<br/>" + tr("Deactivated"),description:"URL <code style=\"font-size:85%\">https://www.testsite.com/</code> " + tr("will be normalized to") + " <code style=\"font-size:85%\">https://www.testsite.com</code>"}]})) %>"></i>
</span></div>
<div><span data-preserve="true" data-preserve-type="check" data-preserve-id="Check9">
	<input type="checkbox" id="Check9" checked="checked" style="margin-left:20px"/> <label for="Check9" class="tr">Remove trailing slash</label> <i class="fa fa-question-circle help-input" data-toggle="tooltip" data-html="true" title="<%= _.escape(_.template($("#tooltip-input").html())({title:tr("Remove trailing slash"),description:tr("If enabled, the trailing slash will be removed from the URL."),examples:[{code:tr("Activated"),description:"URL <code style=\"font-size:85%\">testsite.com/info/</code> " + tr("will be normalized to") + " <code style=\"font-size:85%\">http://testsite.com/info</code>"},{code:"<br/>" + tr("Deactivated"),description:"URL <code style=\"font-size:85%\">testsite.com/info/</code> " + tr("will be normalized to") + " <code style=\"font-size:85%\">http://testsite.com/info/</code>"}]})) %>"></i>
</span></div>
<div><span data-preserve="true" data-preserve-type="check" data-preserve-id="Check10">
	<input type="checkbox" id="Check10" checked="checked" style="margin-left:20px"/> <label for="Check10" class="tr">Sort query parameters</label> <i class="fa fa-question-circle help-input" data-toggle="tooltip" data-html="true" title="<%= _.escape(_.template($("#tooltip-input").html())({title:tr("Sort query parameters"),description:tr("If enabled, the query parameters will be sorted alphabetically by name."),examples:[{code:tr("Activated"),description:"URL <code style=\"font-size:85%\">https://testsite.com/api.php?b=two&a=one&c=three</code> " + tr("will be normalized to") + " <code style=\"font-size:85%\">https://testsite.com/api.php?a=one&b=two&c=three</code>"},{code:"<br/>" + tr("Deactivated"),description:"URL <code style=\"font-size:85%\">testsite.com/api.php?b=two&a=one&c=three</code> " + tr("will be normalized to") + " <code style=\"font-size:85%\">http://testsite.com/api.php?b=two&a=one&c=three</code>"}]})) %>"></i>
</span></div>
<%= _.template($('#variable_constructor').html())({id:"Save", description:tr("Variable to save the result"), default_variable: "NORMALIZED_URL", help: {description: tr("Variable in which, after successful execution of the action, the final URL will be written."), examples:[{code:"https://en.wikipedia.org/wiki/URL"},{code:"</br>http://fingerprints.bablosoft.com/#testing"},{code:"</br>http://rucaptcha.com/in.php?key=1abc234de56fab7c89012d34e56fa7b8</br>&method=userrecaptcha&version=enterprise&action=verify</br>&min_score=0.3</br>&googlekey=6LfZil0UAAAAAAdm1Dpzsw9q0F11-bmervx9g5fE&pageurl=http://mysite.com/page"}]} }) %>
</div>
<div class="tooltipinternal">
	<div class="tr tooltip-paragraph-first-fold">Normalize URL.</div>
	<div class="tooltip-paragraph-fold"><span class="tr">This action will return a string containing the URL, normalized according to the specified parameters.</span> <span class="tr">You can learn more about the URL normalization in <a href="#" onclick="BrowserAutomationStudio_OpenUrl('https://en.wikipedia.org/wiki/URI_normalization');return false">Wiki</a>.</span></div>
	<div class="tr tooltip-paragraph-fold">For example, the URL <code>"www.site.com/api.php?b=two&a=one&c=three"</code> will be normalized to <code>"https://site.com/api.php?a=one&b=two&c=three"</code> if "https" is specified in the "Default protocol" parameter and the "Strip WWW", "Sort query parameters" parameters are enabled.</div>
	<div class="tooltip-paragraph-fold"><span class="tr">The "Normalize Protocol" parameter is responsible for normalizing the relative protocol. You can learn more about the relative protocol in</span> <a href="#" onclick="BrowserAutomationStudio_OpenUrl('https://en.wikipedia.org/wiki/Wikipedia:Protocol-relative_URL');return false">Wiki</a>.</div>
	<div class="tr tooltip-paragraph-fold">You can get a list of links from a string using the "Extract all links" action from the "String" module.</div>
	<div class="tr tooltip-paragraph-fold">You can parse a link to items using the "Parse URL" action.</div>
	<div class="tr tooltip-paragraph-fold">You can generate a link from items using the "Generate URL" action.</div>
	<div class="tr tooltip-paragraph-last-fold">You can change link items using the "Change URL" action.</div>
</div>
<%= _.template($('#back').html())({action:"executeandadd", visible:true}) %>
