<div class="container-fluid">
<%= _.template($('#input_constructor').html())({id:"url", description: tr("URL"), default_selector: "string", disable_int:true, value_string: "", help: {description: tr("String containing the URL with want to parse."),examples:[{code:"https://en.wikipedia.org/wiki/URL"},{code:"</br>https://fingerprints.bablosoft.com/#testing"},{code:"</br>https://rucaptcha.com/in.php?key=1abc234de56fab7c89012d34e56fa7b8</br>&method=userrecaptcha&version=enterprise&action=verify</br>&min_score=0.3</br>&googlekey=6LfZil0UAAAAAAdm1Dpzsw9q0F11-bmervx9g5fE&pageurl=http://mysite.com/page/"}]} }) %>
<%= _.template($('#variable_constructor').html())({id:"protocol", description:tr("Protocol/Scheme"), default_variable: "PARSED_URL_PROTOCOL", help: {description: tr("This variable will contain the protocol/scheme of the specified URL.") + " " + tr("The scheme of accessing a resource, in most cases, means a network protocol."), examples:[{code:"https"},{code:"http"},{code:"ws"},{code:"ftp"},{code:tr("Empty string"), description: tr("The specified URL does not contain the protocol/scheme")}]} }) %>
<%= _.template($('#variable_constructor').html())({id:"username", description:tr("Username"), default_variable: "PARSED_URL_USERNAME", help: {description: tr("This variable will contain the username of the specified URL.") + " " + tr("The username used to access the resource."), examples:[{code:"user1"},{code:"login321"},{code:"myname"},{code:tr("Empty string"), description: tr("The specified URL does not contain a username")}]} }) %>
<%= _.template($('#variable_constructor').html())({id:"password", description:tr("Password"), default_variable: "PARSED_URL_PASSWORD", help: {description: tr("This variable will contain the password for the specified user."), examples:[{code:"pass123"},{code:"mypassword111"},{code:"goodpass"},{code:tr("Empty string"), description: tr("The specified URL does not contain a password")}]} }) %>
<%= _.template($('#variable_constructor').html())({id:"host", description:tr("Host"), default_variable: "PARSED_URL_HOST", help: {description: tr("This variable will contain the hostname or ip (IPv4 or IPv6) of the specified URL."), examples:[{code:"en.wikipedia.org"},{code:"fingerprints.bablosoft.com"},{code:"rucaptcha.com"},{code:"127.0.0.1"},{code:"[2a00:1450:4025:401::67]"}]} }) %>
<%= _.template($('#variable_constructor').html())({id:"port", description:tr("Port"), default_variable: "PARSED_URL_PORT", help: {description: tr("This variable will contain the port of the specified URL."), examples:[{code:80},{code:443},{code:21},{code:tr("Empty string"), description: tr("The specified URL does not contain a port")}]} }) %>
<%= _.template($('#variable_constructor').html())({id:"path", description:tr("Path"), default_variable: "PARSED_URL_PATH", help: {description: tr("This variable will contain the path of the specified URL.") + " " + tr("The path specifies information about the location of the resource."), examples:[{code:"/wiki/URL"},{code:"/"},{code:"/in.php"}]} }) %>
<%= _.template($('#variable_constructor').html())({id:"query", description:tr("Query"), default_variable: "PARSED_URL_QUERY", help: {description: tr("This variable will contain an object consisting of query parameters and their values obtained from the specified URL.") + " " + tr("The query is the part of the URL that starts with the \"?\" character, parameters are separated by \"&\", and parameter name and value are separated by \"=\"."), examples:[{code:"{\"foo\":\"bar\"}"},{code:"</br>{\"query\":\"string\"}"},{code:"</br>{\"key\":\"1abc234de56fab7c89012d34e56fa7b8\", \"method\":\"userrecaptcha\", \"version\":\"enterprise\", \"action\":\"verify\", \"min_score\":0.3, \"googlekey\":\"6LfZil0UAAAAAAdm1Dpzsw9q0F11-bmervx9g5fE\", \"pageurl\":\"http://mysite.com/page/\"}"},{code:"</br>{ }", description: tr("The specified URL does not contain query parameters")}]} }) %>
<%= _.template($('#variable_constructor').html())({id:"hash", description:tr("Fragment"), default_variable: "PARSED_URL_FRAGMENT", help: {description: tr("This variable will contain the fragment of the specified URL.") + " " + tr("Fragment is the part of the URL that starts with the \"#\" character and can indicate a title within a document or the id attribute of an element. Following the link with the fragment, the browser will open the page and move the window to the specified element."), examples:[{code:"info"},{code:"testing"},{code:"solving_recaptcha_enterprise"},{code:tr("Empty string"), description: tr("The specified URL does not contain the fragment")}]} }) %>
<%= _.template($('#block_start').html())({id:"Additional", name: tr("Additional settings"), description: ""}) %>
<%= _.template($('#input_constructor').html())({id:"base_url", description: tr("Base URL"), default_selector: "string", disable_int:true, value_string: "", help: {description: tr("Optional parameter.") + " " + tr("The URL used when the main URL is relative."),examples:[{code:"https://en.wikipedia.org"},{code:"https://fingerprints.bablosoft.com"},{code:"https://rucaptcha.com"}]} }) %>
<div><span data-preserve="true" data-preserve-type="check" data-preserve-id="Check">
	<input type="checkbox" id="Check" checked="checked" style="margin-left:25px"/> <label for="Check" class="tr">Normalize URL before parsing</label>
</span></div>
<div><span data-preserve="true" data-preserve-type="check" data-preserve-id="Check2">
	<input type="checkbox" id="Check2" checked="checked" style="margin-left:25px"/> <label for="Check2" class="tr">Complete action with fail if an invalid URL is specified</label>
</span></div>
<%= _.template($('#block_end').html())() %>
</div>
<div class="tooltipinternal">
	<div class="tr tooltip-paragraph-first-fold">Parse the URL string into items.</div>
	<div class="tooltip-paragraph-fold"><span class="tr">This action will save each item of the URL to its own variable.</span> <span class="tr">You can learn more about URL in <a href="#" onclick="BrowserAutomationStudio_OpenUrl('https://en.wikipedia.org/wiki/URL');return false">Wiki</a>.</span></div>
	<div class="tr tooltip-paragraph-fold">The query is saved as an object, where the key is the parameter name and the value is the parameter value.</div>
	<div class="tr tooltip-paragraph-fold">To get the value of the query parameter, use the JPath query <span style="color:black">$.key</span>, where key is the name of the parameter, in the "Get value" action from the "JSON" module.</div>
	<div class="tooltip-paragraph-fold"><span class="tr">Before parsing, you can normalize the URL by activating the corresponding parameter in the additional settings, or use the "Normalize URL" action for flexible normalization.</span> <span class="tr">You can learn more about the URL normalization in <a href="#" onclick="BrowserAutomationStudio_OpenUrl('https://en.wikipedia.org/wiki/URI_normalization');return false">Wiki</a>.</span></div>
	<div class="tr tooltip-paragraph-fold">You can get a list of links from a string using the "Extract all links" action from the "String" module.</div>
	<div class="tr tooltip-paragraph-fold">You can generate a link from items using the "Generate URL" action.</div>
	<div class="tr tooltip-paragraph-fold">You can change link items using the "Change URL" action.</div>
	<div class="tr tooltip-paragraph-last-fold">If an invalid URL is specified, the thread will stop with fail message. If you want to continue thread, use "Ignore errors" action, or deactivate the corresponding parameter in the additional settings.</div>
</div>
<%= _.template($('#back').html())({action:"executeandadd", visible:true}) %>
