<div class="container-fluid">
<%= _.template($('#input_constructor').html())({id:"FilePath", description: tr("File path"), default_selector: "string", disable_int:true, value_string: "", help: {description:tr("The path to the excel file."),examples:[{code:"{{excel_file}}"},{code:"C:/test.xlsx"},{code:"C:/Program Files/test1.xlsx"},{code:"C:/Program Files/test2.xlsx"}]} }) %>
<%= _.template($('#input_constructor').html())({id:"SheetIndexOrName", description: tr("Sheet index or name") + ". " + tr("Can be blank"), default_selector: "int", value_number: "", min_number:0, max_number:999999, help: {description: tr("Index or sheet name in excel file."),examples:[{code:0, description: tr("First sheet index")}, {code:1, description: tr("Second sheet index")}, {code:tr("Sheet1"), description: tr("First sheet name")}, {code:tr("Sheet2"), description: tr("Second sheet name")}, {code:tr("Empty string"), description: tr("Search all sheets of excel file")}]} }) %>
<%= _.template($('#input_constructor').html())({id:"Contains", description: tr("Cell contains"), default_selector: "string", disable_int:true, value_string: "", help: {description: tr("The data which will be searched.")} }) %>
<%= _.template($('#variable_constructor').html())({id:"Column", description: tr("Column index of the found cell"), default_variable: "XLSX_FOUND_COLUMN", help: {description: tr("Variable in which, after successful execution of the action, the column index of the found cell will be written."),examples:[{code:0, description:tr("First column")},{code:1, description:tr("Second column")},{code:tr("Empty string"), description: tr("Cell not found")}]}}) %>
<%= _.template($('#variable_constructor').html())({id:"Row", description: tr("Row index of the found cell"), default_variable: "XLSX_FOUND_ROW", help: {description: tr("Variable in which, after successful execution of the action, the row index of the found cell will be written."),examples:[{code:0, description:tr("First row")},{code:1, description:tr("Second row")},{code:tr("Empty string"), description: tr("Cell not found")}]}}) %>
<%= _.template($('#variable_constructor').html())({id:"Sheet", description: tr("Sheet index of the found cell"), default_variable: "XLSX_FOUND_SHEET_INDEX", help: {description: tr("Variable in which, after successful execution of the action, the index of the sheet of the found cell will be written."),examples:[{code:0, description: tr("First sheet index")}, {code:1, description: tr("Second sheet index")},{code:tr("Empty string"), description: tr("Cell not found")}]}}) %>
</div>
<div class="tooltipinternal">
	<div class="tr tooltip-paragraph-first-fold">Find single cell by its content in excel file.</div>
	<div class="tr tooltip-paragraph-fold">This action save in variables the column, row and sheet indexes of the found cell or empty strings if the cell was not found.</div>
	<div class="tr tooltip-paragraph-fold">If a resource is specified in the "File path" parameter, resource location will be used.</div>
	<div class="tr tooltip-paragraph-last-fold">If an error occurred while execute action, the thread will stop with fail message. If you want to continue thread, use "Ignore errors" action.</div>
</div>
<%= _.template($('#back').html())({action:"executeandadd",use_timeout: true, visible:true}) %>