<div class="container-fluid">
<%= _.template($('#input_constructor').html())({id:"FilePath", description: tr("File path"), default_selector: "string", disable_int:true, value_string: "", help: {description:tr("The path to the excel file."),examples:[{code:"{{excel_file}}"},{code:"C:/test.xlsx"},{code:"C:/Program Files/test1.xlsx"},{code:"C:/Program Files/test2.xlsx"}]} }) %>
<%= _.template($('#input_constructor').html())({id:"SheetIndexOrName", description: tr("Sheet index or name"), default_selector: "int", value_number: 0, min_number:0, max_number:999999, help: {description: tr("Index or sheet name in excel file."),examples:[{code:0, description: tr("First sheet index")}, {code:1, description: tr("Second sheet index")}, {code:tr("Sheet1"), description: tr("First sheet name")}, {code:tr("Sheet2"), description: tr("Second sheet name")}]} }) %>
<%= _.template($('#input_constructor').html())({id:"FromRow", description: tr("From row") + ". " + tr("Can be blank"), default_selector: "int", disable_string:true, value_number: "", min_number:-1, max_number:999999, help: {description: tr("Row index from which deleting starts."),examples:[{code:-1, description:tr("Last row")},{code:0, description:tr("First row")},{code:1, description:tr("Second row")},{code:tr("Empty string"), description: tr("First row")}]} }) %>
<%= _.template($('#input_constructor').html())({id:"ToRow", description: tr("To row") + ". " + tr("Can be blank"), default_selector: "int", disable_string:true, value_number: "", min_number:-1, max_number:999999, help: {description: tr("Row index after which deleting ends."),examples:[{code:-1, description:tr("Up to and including last row")},{code:0, description:tr("Up to and including first row")},{code:1, description:tr("Up to and including second row")},{code:tr("Empty string"), description: tr("Up to and including last row")}]} }) %>
</div>
<div class="tooltipinternal">
	<div class="tr tooltip-paragraph-first-fold">Delete rows from specified excel file.</div>
	<div class="tr tooltip-paragraph-fold">Rows following the deleted rows will be shifted up.</div>
	<div class="tr tooltip-paragraph-fold">Removing row is performed up to and including row specified in "To row" parameter. To delete one row, you need to specify its index in both parameters.</div>
	<div class="tr tooltip-paragraph-fold">If the "From row" and "To row" parameters are not specified, all rows will be deleted.</div>
	<div class="tr tooltip-paragraph-fold">If the "From row" parameter is specified and the "To row" parameter is not specified, all rows from the specified to the last will be deleted.</div>
	<div class="tr tooltip-paragraph-fold">If the "From row" parameter is not specified and the "To row" parameter is specified, all rows from the first to the specified will be deleted.</div>
	<div class="tr tooltip-paragraph-fold">If a resource is specified in the "File path" parameter, resource location will be used.</div>
	<div class="tr tooltip-paragraph-last-fold">If an error occurred while execute action, the thread will stop with fail message. If you want to continue thread, use "Ignore errors" action.</div>
</div>
<%= _.template($('#back').html())({action:"executeandadd",use_timeout: true,use_waiter: true,waiter_enabled: true,waiter_title: "Wait until the file will be written, it may take additional time. In case if this option is checked, error will be thrown if file could not be saved.",visible:true}) %>