<div class="container-fluid">
<%= _.template($('#input_constructor').html())({id:"Protocol", description:tr("Protocol"), default_selector: "string", variants:["SFTP","FTP","SSH<br/><span style='color:gray;font-size:small'>SCP</span>"], disable_int:true, value_string: "SFTP", help: {description: tr("The protocol by which the connection to the remote server will be made.")} }) %>
<%= _.template($('#input_constructor').html())({id:"Host", description:tr("Host name"), default_selector: "string", disable_int:true, value_string: "", help: {description: tr("Host (URL or IP) of the remote server."),examples:[{code:"ftp.site.com"},{code:"ftp15.testsite.com"},{code:"96.256.27.26"}]} }) %>
<%= _.template($('#input_constructor').html())({id:"Port", description:tr("Port"), variants:["auto<br/><span style='color:gray;font-size:small'>" + tr("Automatically detect port based on protocol") + "</span>","21<br/><span style='color:gray;font-size:small'>" + tr("Default port for FTP protocol") + "</span>","22<br/><span style='color:gray;font-size:small'>" + tr("Default port for SFTP and SSH protocols") + "</span>"], default_selector: "string", disable_int:true, value_string: "auto", help: {description: tr("Port of the remote server."),examples:[{code:"auto",description:tr("Automatically detect port based on protocol")},{code:"21",description:tr("Default port for FTP protocol")},{code:"22",description:tr("Default port for SFTP and SSH protocols")}]} }) %>
<%= _.template($('#input_constructor').html())({id:"Username", description:tr("Username"), default_selector: "string", disable_int:true, value_string: "", help: {description: tr("Username of the remote server.")} }) %>
<%= _.template($('#input_constructor').html())({id:"Password", description:tr("Password"), default_selector: "string", disable_int:true, value_string: "", help: {description: tr("Password of the remote server.")} }) %>
<%= _.template($('#input_constructor').html())({id:"Timeout", description:tr("Timeout (seconds)"), default_selector: "int", disable_string:true, value_number: 300, min_number:0, max_number:999999, help: {description: tr("This action won't start connection, it only sets configuration. Connection will be established after first attempt to access server. When action, which triggers connection will be finished, connection won't be closed immediately. It will be preserved for a time specified in this parameter. If another action will require access to server, connection will be reused.")} }) %>
</div>
<div class="tooltipinternal">
	<div class="tr tooltip-paragraph-first-fold">Configure access to a remote FTP or SSH server.</div>
	<div class="tr tooltip-paragraph-fold">This action should be called once before any other action that works with the remote server.</div>
	<div class="tr tooltip-paragraph-fold">This action won't start connection, it only sets configuration. Connection will be established after first attempt to access server. When action, which triggers connection will be finished, connection won't be closed immediately. It will be preserved for a time specified in "Timeout" parameter. If another action will require access to server, connection will be reused.</div>
	<div class="tr tooltip-paragraph-fold">You don't need to close connection explicitly, it will be closed automatically after timeout or when the script will stop.</div>

	<div class="tooltip-paragraph-fold"><span class="tr">FTP (File Transfer Protocol) is a standard network protocol used to transfer files between a client and a server. If you have VPS or VDS, you need to install FTP server first in order to use FTP connection type.</span> (<a href="#" onclick="BrowserAutomationStudio_OpenUrl('https://www.digitalocean.com/community/tutorials/how-to-set-up-vsftpd-for-a-user-s-directory-on-ubuntu-18-04'); return false;"><span class="tr">Instructions</span></a>).</div>
	<div class="tr tooltip-paragraph-fold">SFTP (Secure File Transfer Protocol) is an alternative to FTP that also allows you to transfer files, but adds a layer of security to the process.</div>
	<div class="tr tooltip-paragraph-last-fold">SSH (Secure Shell) allows to execute commands and transfer files on remote VPS or VDS. Every connection is encrypted. When you rent a remote Linux server, hosting always provides SSH access.</div>
</div>
<%= _.template($('#back').html())({action:"executeandadd", visible:true}) %>
