<div class="container-fluid">
<%= _.template($('#input_constructor').html())({id:"item1", description:tr("Item") + " 1. " + tr("Can be blank"), default_selector: "string", disable_int:true, value_string: "", help: {description: tr("The item to add to the CSV string."),examples:[{code:tr("Just sample text")},{code:5},{code:true},{code:tr("Empty string"), description: tr("The parameters \"Item 2\", \"Item 3\", \"List of items\" will be used")}]} }) %>
<%= _.template($('#input_constructor').html())({id:"item2", description:tr("Item") + " 2. " + tr("Can be blank"), default_selector: "string", disable_int:true, value_string: "", help: {description: tr("The item to add to the CSV string."),examples:[{code:tr("Just sample text")},{code:5},{code:true},{code:tr("Empty string"), description: tr("The parameters \"Item 1\", \"Item 3\", \"List of items\" will be used")}]} }) %>
<%= _.template($('#input_constructor').html())({id:"item3", description:tr("Item") + " 3. " + tr("Can be blank"), default_selector: "string", disable_int:true, value_string: "", help: {description: tr("The item to add to the CSV string."),examples:[{code:tr("Just sample text")},{code:5},{code:true},{code:tr("Empty string"), description: tr("The parameters \"Item 1\", \"Item 2\", \"List of items\" will be used")}]} }) %>
<%= _.template($('#input_constructor').html())({id:"items_list", description:tr("List of items") + ". " + tr("Can be blank"), default_selector: "string", disable_int:true, value_string: "", help: {description: tr("List of items to add to the CSV string.") + " " + tr("As a list, you can use a string consisting of strings, separated by commas."),examples:[{code:tr("Just sample text") + ",Test text,string"},{code:tr("Just sample text") + ", Test text, string"},{code:"[\"" + tr("Just sample text") + "\", \"Test text\", \"string\"]"},{code:tr("Empty string"), description: tr("The parameters \"Item 1\", \"Item 2\", \"Item 3\" will be used")}]} }) %>
<%= _.template($('#input_constructor').html())({id:"separator", description: tr("Separator"), default_selector: "string", disable_int:true, value_string: ":", help: {description: tr("Separator to insert between elements of CSV string."),examples:[{code:'","',description:tr("Just sample text") + ",Test text,string"},{code:'" "',description:tr("Just sample text") + " Test text string"},{code:'", "',description:tr("Just sample text") + ", Test text, string"},{code:tr("Empty string"), description: '":"'}]} }) %>
<%= _.template($('#variable_constructor').html())({id:"Save", description:tr("Variable to save the result"), default_variable: "CSV_STRING", help: {description: tr("Variable in which, after successful execution of the action, the CSV string will be written."), examples:[{code:"login:password"},{code:"id,name,login"},{code:tr("Just sample text") + ";Test text;string"}]} }) %>
</div>
<div class="tooltipinternal">
	<div class="tr tooltip-paragraph-first-fold">Create CSV string from multiple items.</div>
	<div class="tr tooltip-paragraph-fold">This action will return a CSV string composed of all the specified items, separated by the specified character.</div>
	<div class="tr tooltip-paragraph-fold">For example, if the parameters "Item 1" and "Item 2" are specified, the values of which are respectively <code>"test"</code> and <code>"text"</code>, and the separator <code>":"</code>, then the action will return <code>"test:text"</code>.</div>
	<div class="tr tooltip-paragraph-fold">Items from separate fields and a list are added to a general list of items that will be joined.</div>
	<div class="tr tooltip-paragraph-fold">For example, if a item is specified in the "Item 1" field and a list of 4 items is specified in the "List of items" field, then 5 items will be joined.</div>
	<div class="tr tooltip-paragraph-fold">If some of the parameters ("Item 1", "Item 2", "Item 3", "List of items") are not specified, all parameters will be used except for them.</div>
	<div class="tr tooltip-paragraph-fold">For example, if "List of items" is not specified, then the list will be formed from the parameters "Item 1" and "Item 2" and "Item 3". If the parameters "Item 1", "Item 2", "Item 3" are empty, then the "List of items" will be used. If all parameters are specified, then all of them will be used.</div>
	<div class="tr tooltip-paragraph-fold">The values of all elements are converted to a string before joining.</div>
	<div class="tr tooltip-paragraph-fold">If the element contains a separator, then it will be enclosed in quotes.</div>
	<div class="tr tooltip-paragraph-fold">The order of joining the fields is as follows "Item 1", "Item 2", "Item 3", "List of items".</div>
	<div class="tr tooltip-paragraph-last-fold">The list can be created using actions from the "List" module.</div>
</div>
<%= _.template($('#back').html())({action:"executeandadd", visible:true}) %>
