<div class="container-fluid">
<%= _.template($('#input_constructor').html())({id:"number", description: tr("Numbеr"), default_selector: "int", disable_string:true, value_number: "", min_number:-999999, max_number:999999, help: {description: tr("The number to format and convert to a string."),examples:[{code:123},{code:100000},{code:1456.578}]} }) %>
<%= _.template($('#input_constructor').html())({id:"decimals", description:tr("Number of decimal places") + ". " + tr("Can be blank"), default_selector: "int", disable_string:true, value_number: "", min_number:-1, max_number:20, help: {description: tr("Optional parameter.") + " " + tr("The number of decimal places to which the number will be rounded."),examples:[{code:4, description:156.6439},{code:2, description:21.78},{code:0, description:tr("Round to whole number")},{code:-1, description:tr("Do not round the number")},{code:tr("Empty string"), description:tr("Do not round the number")}]} }) %>
<%= _.template($('#input_constructor').html())({id:"digits", description:tr("Minimum number of characters in the number") + ". " + tr("Can be blank"), default_selector: "int", disable_string:true, value_number: "", min_number:0, max_number:999999, help: {description: tr("Optional parameter.") + " " + tr("The minimum number of characters in a number. If the number of characters is less than the specified number, then zeros will be added to the place of missing characters before the number."),examples:[{code:4, description:"0321"},{code:2, description:"01"},{code:0, description:tr("Don't change the number of characters")},{code:tr("Empty string"), description:tr("Don't change the number of characters")}]} }) %>
<%= _.template($('#input_constructor').html())({id:"dec_point", description: tr("Decimal separator") + ". " + tr("Can be blank"), default_selector: "string", value_string: ".", help: {description: tr("Optional parameter.") + " " + tr("Separator between integer and decimal parts of a number."),examples:[{code:'"."', description:156.6439},{code:'","', description:"156,6439"},{code:tr("Empty string"), description:tr('"." - 156.6439')}]} }) %>
<%= _.template($('#input_constructor').html())({id:"thousands_sep", description: tr("Thousandth separator") + ". " + tr("Can be blank"), default_selector: "string", value_string: ",", help: {description: tr("Optional parameter.") + " " + tr("Separator between thousandths."),examples:[{code:'" "', description:"1 000 000.01"},{code:'","', description:"1,000,000.01"},{code:tr("Empty string"), description:tr('"," - 1,000,000.01')}]} }) %>
<%= _.template($('#variable_constructor').html())({id:"Save", description:tr("Variable to save the result"), default_variable: "FORMATTED_NUMBER", help: {description: tr("Variable in which, after successful execution of the action, the formatted string representation of the specified number will be written."),examples:[{code:"123"},{code:"100,000"},{code:"1,456.578"}]}}) %>
</div>
<div class="tooltipinternal">
	<div class="tr tooltip-paragraph-first-fold">Format and convert the specified number to a string.</div>
	<div class="tr tooltip-paragraph-fold">This action can bring the number into a more readable form, for example, for further output to the log.</div>
	<div class="tr tooltip-paragraph-fold">Before formatting, the number can be rounded by specifying the "Number of decimal places" parameter.</div>
	<div class="tr tooltip-paragraph-fold">This action will return the formatted string representation of the specified number.</div>
	<div class="tr tooltip-paragraph-last-fold">For example, the number <code>1967567.3245</code> will be converted to the string <code>"1 967 567.3245"</code> if a comma is specified in the "Decimal separator" parameter, and a space is specified in the "Thousandth separator" parameter.</div>
</div>
<%= _.template($('#back').html())({action:"executeandadd", visible:true}) %>
